### ISSUE TITLE
No shared cipher

### ISSUE THREAD

**Issue by sobrinho** [socketry/falcon#13]
Added to Gemfile and ran `bundle exec falcon serve`:

```
λ bundle exec falcon serve
DEPRECATION WARNING: You have Rails 2.3-style plugins in vendor/plugins! Support for these plugins will be removed in Rails 4.0. Move them out and bundle them in your Gemfile, or fold them in to your app as lib/myplugin/* and config/initializers/myplugin.rb. See the release notes for more on this: http://weblog.rubyonrails.org/2012/1/4/rails-3-2-0-rc2-has-been-released. (called from <top (required)> at /Users/sobrinho/Developer/omitted/config/environment.rb:5)
DEPRECATION WARNING: You have Rails 2.3-style plugins in vendor/plugins! Support for these plugins will be removed in Rails 4.0. Move them out and bundle them in your Gemfile, or fold them in to your app as lib/myplugin/* and config/initializers/myplugin.rb. See the release notes for more on this: http://weblog.rubyonrails.org/2012/1/4/rails-3-2-0-rc2-has-been-released. (called from <top (required)> at /Users/sobrinho/Developer/omitted/config/environment.rb:5)
Expected string default value for '--helper'; got true (boolean)
I, [2018-08-09T09:50:06.321984 #141]  INFO -- : Falcon taking flight! Binding to #<Falcon::Endpoint https://localhost:9292/ {:reuse_port=>true}> [Async::Container::Forked with concurrency: 4]
I, [2018-08-09T09:50:06.326142 #157]  INFO -- : Send `kill -USR1 157` for detailed status :)
I, [2018-08-09T09:50:06.326692 #159]  INFO -- : Send `kill -USR1 159` for detailed status :)
I, [2018-08-09T09:50:06.326987 #160]  INFO -- : Send `kill -USR1 160` for detailed status :)
I, [2018-08-09T09:50:06.328072 #161]  INFO -- : Send `kill -USR1 161` for detailed status :)
E, [2018-08-09T09:50:08.961224 #161] ERROR -- #<Async::IO::SSLServer:0x00007fb20551c520>: SSL_accept returned=1 errno=0 state=error: no shared cipher (OpenSSL::SSL::SSLError)
/Users/sobrinho/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/async-io-1.15.2/lib/async/io/generic.rb:128:in `accept_nonblock'
/Users/sobrinho/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/async-io-1.15.2/lib/async/io/generic.rb:128:in `async_send'
/Users/sobrinho/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/async-io-1.15.2/lib/async/io/generic.rb:47:in `block in wrap_blocking_method'
/Users/sobrinho/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/async-io-1.15.2/lib/async/io/ssl_socket.rb:118:in `block in accept'
/Users/sobrinho/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/async-1.10.1/lib/async/task.rb:74:in `block in initialize'
E, [2018-08-09T09:50:08.997884 #157] ERROR -- #<Async::IO::SSLServer:0x00007fb20551c520>: SSL_accept returned=1 errno=0 state=error: no shared cipher (OpenSSL::SSL::SSLError)
/Users/sobrinho/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/async-io-1.15.2/lib/async/io/generic.rb:128:in `accept_nonblock'
/Users/sobrinho/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/async-io-1.15.2/lib/async/io/generic.rb:128:in `async_send'
/Users/sobrinho/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/async-io-1.15.2/lib/async/io/generic.rb:47:in `block in wrap_blocking_method'
/Users/sobrinho/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/async-io-1.15.2/lib/async/io/ssl_socket.rb:118:in `block in accept'
/Users/sobrinho/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/async-1.10.1/lib/async/task.rb:74:in `block in initialize'
E, [2018-08-09T09:50:09.001011 #157] ERROR -- #<Async::IO::SSLServer:0x00007fb20551c520>: SSL_accept returned=1 errno=0 state=error: inappropriate fallback (OpenSSL::SSL::SSLError)
/Users/sobrinho/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/async-io-1.15.2/lib/async/io/generic.rb:128:in `accept_nonblock'
/Users/sobrinho/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/async-io-1.15.2/lib/async/io/generic.rb:128:in `async_send'
/Users/sobrinho/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/async-io-1.15.2/lib/async/io/generic.rb:47:in `block in wrap_blocking_method'
/Users/sobrinho/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/async-io-1.15.2/lib/async/io/ssl_socket.rb:118:in `block in accept'
/Users/sobrinho/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/async-1.10.1/lib/async/task.rb:74:in `block in initialize'
```

Legacy project using ruby 2.3 and rails 3.2.

Maybe related?

**Comment by ioquatix** [comment]
Hmm, I will try it. What web browser were you using?

**Comment by ioquatix** [comment]
I think this should be fixed in the latest release of `localhost`. You shouldn't need to delete your existing certificates, but if it doesn't automatically regenerate them, try trashing `~/.localhost/*.{crt,key}`

**Comment by sobrinho** [comment]
Same issue, not working neither in Chrome, Safari or cURL.

```
λ curl http://localhost:9292
curl: (56) Recv failure: Connection reset by peer

λ curl https://localhost:9292
curl: (35) error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
```

<img width="638" alt="screen shot 2018-08-10 at 10 45 48" src="https://user-images.githubusercontent.com/26460/43961218-b15ecc80-9c8a-11e8-8894-b39bd9d73015.png">

**Comment by sobrinho** [comment]
And I removed, generated and installed the ~/.localhost certificate again, does not seem to be related to that.

Maybe falcon, or its dependencies, isn't compatible with ruby 2.3.6?

**Comment by ioquatix** [comment]
Ruby 2.3 is definitely supported. However, there is another aspect to this which is underspecified - your OpenSSL version, and the version which was used to compile Ruby in the first instance.

Do you think you can clone the `localhost` and `falcon` repos and run the unit tests locally?

In the source root simply run `bundle install && rspec`. If there are failures it will help to narrow down the issue.

**Comment by ioquatix** [comment]
(I'm also assuming you did bundle update before retrying the tests?)

**Comment by sobrinho** [comment]
Yes, I did.

I'm going to try to spec both projects, just a sec.

**Comment by sobrinho** [comment]
Both passed all green.

**Comment by sobrinho** [comment]
Going to try with a fresh sinatra app, just a sec.

**Comment by sobrinho** [comment]
Same issue 😱

**Comment by ioquatix** [comment]
Hmm, odd. Let me try it here.

**Comment by sobrinho** [comment]
I'm going to try with different ruby versions, doesn't seem to be related with rails then.

**Comment by ioquatix** [comment]
Can you show me your `Gemfile.lock`?

**Comment by sobrinho** [comment]
```
GEM
  remote: https://rubygems.org/
  specs:
    async (1.10.1)
      nio4r (~> 2.3)
      timers (~> 4.1)
    async-container (0.6.0)
      async (~> 1.0)
      async-io (~> 1.4)
    async-http (0.30.3)
      async (~> 1.6)
      async-io (~> 1.15)
      http-protocol (~> 0.3.0)
    async-io (1.15.2)
      async (~> 1.3)
    falcon (0.18.4)
      async-container (~> 0.6.0)
      async-http (~> 0.30.0)
      async-io (~> 1.9)
      localhost (~> 1.1)
      rack (>= 1.0)
      samovar (~> 1.3)
    hitimes (1.3.0)
    http-hpack (0.1.0)
    http-protocol (0.3.0)
      http-hpack (~> 0.1.0)
    localhost (1.1.2)
    mapping (1.1.1)
    mustermann (1.0.2)
    nio4r (2.3.1)
    rack (2.0.5)
    rack-protection (2.0.3)
      rack
    rainbow (2.2.2)
      rake
    rake (12.3.1)
    samovar (1.9.0)
      mapping (~> 1.0)
      rainbow (~> 2.0)
    sinatra (2.0.3)
      mustermann (~> 1.0)
      rack (~> 2.0)
      rack-protection (= 2.0.3)
      tilt (~> 2.0)
    tilt (2.0.8)
    timers (4.1.2)
      hitimes

PLATFORMS
  ruby

DEPENDENCIES
  falcon
  sinatra

BUNDLED WITH
   1.16.1
```

This is already from the fresh sinatra app.

**Comment by ioquatix** [comment]
That all looks good. And your ruby version is 2.3.6? or 2.3.7?

**Comment by sobrinho** [comment]
Aha!

2.3.6: bug
2.4.4: works
2.5.1: works

**Comment by sobrinho** [comment]
Let me try compiling 2.3.7

**Comment by ioquatix** [comment]
On 2.3.6, what is the result of `OpenSSL::SSL::SSLContext.instance_methods(false).include? :alpn_protocols` (`require 'openssl'` first)

**Comment by sobrinho** [comment]
```
pwd:falcon-example   ref:   ruby:2.3.6   node:v9.10.1   status:0
λ irb
(main) normal> require 'openssl'
=> true
(main) normal> OpenSSL::SSL::SSLContext.instance_methods(false).include? :alpn_protocols
=> true
```

**Comment by sobrinho** [comment]
Another interesting issue, in case you already didn't know, hitting the falcon port using http fails instead of redirecting to https.

**Comment by ioquatix** [comment]
`falcon` doesn't currently redirect from http to https since it expects SSL on the specific port you give it rather than port 80/443.

**Comment by ioquatix** [comment]
Can you tell me `OpenSSL::OPENSSL_LIBRARY_VERSION` from 2.3.6 too?

**Comment by sobrinho** [comment]
```
(main) normal> require 'openssl'
=> true
(main) normal> OpenSSL::OPENSSL_LIBRARY_VERSION
=> "OpenSSL 1.0.2o  27 Mar 2018"
(main) normal> RUBY_VERSION
=> "2.3.6"
```

**Comment by sobrinho** [comment]
Same for 2.4.4:

```
(main) normal> require 'openssl'
=> true
(main) normal> OpenSSL::OPENSSL_LIBRARY_VERSION
=> "OpenSSL 1.0.2o  27 Mar 2018"
(main) normal> RUBY_VERSION
=> "2.4.4"
```

**Comment by sobrinho** [comment]
2.3.7 fails in the same way.

I'm in macOS, btw.

**Comment by ioquatix** [comment]
Hmm, that's a really recent version. It shouldn't have any issues. Also, falcon tests passed. But those tests actually check the server is running, etc.

**Comment by sobrinho** [comment]
Do they perform a real request to see if it is responding?

**Comment by ioquatix** [comment]
Yes.

**Comment by sobrinho** [comment]
Using ruby 2.3.7 with the fresh rack application the Chrome message changed a bit:

<img width="615" alt="screen shot 2018-08-10 at 11 44 06" src="https://user-images.githubusercontent.com/26460/43964223-b5efca9e-9c92-11e8-8323-f823b22c9bf3.png">

**Comment by ioquatix** [comment]
Let me try it on my end and I'll see if I can reproduce.

**Comment by sobrinho** [comment]
No secret but just in case: https://github.com/sobrinho/falcon-issue-13

**Comment by ioquatix** [comment]
I'm just installing 2.3.6 now hold on...

**Comment by ioquatix** [comment]
I could repro... hold on let me see what is going on..

In the mean time, `falcon serve --bind http://localhost:9292` works.

**Comment by sobrinho** [comment]
But in this way we lose the SSL, right?

**Comment by ioquatix** [comment]
Yep and HTTP/2 but it's something that does work in the mean time until I figure out what is wrong with the SSLContext.

**Comment by sobrinho** [comment]
np, thanks!

**Comment by ioquatix** [comment]
I think Ruby 2.3 is broken.

Even thought I specify TLS SSLContext, it still tries to negotiate SSLv3. And this causes the client a lot of confusion it seems:

Ruby 2.3.6:

```
> curl --verbose -k https://localhost:9292
* Rebuilt URL to: https://localhost:9292/
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 9292 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /opt/local/share/curl/curl-ca-bundle.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Unknown (21):
* TLSv1.2 (IN), TLS alert, Server hello (2):
* error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
* Closing connection 0
curl: (35) error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
```

Ruby 2.5

```
> curl --verbose -k https://localhost:9292
* Rebuilt URL to: https://localhost:9292/
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 9292 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /opt/local/share/curl/curl-ca-bundle.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Request CERT (13):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: O=Development/CN=localhost
*  start date: Aug 10 00:31:43 2018 GMT
*  expire date: Aug  7 00:31:43 2028 GMT
*  issuer: O=Development/CN=localhost
*  SSL certificate verify result: self signed certificate (18), continuing anyway.
> GET / HTTP/1.1
> Host: localhost:9292
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 200
< content-type: text/html;charset=utf-8
< x-xss-protection: 1; mode=block
< x-content-type-options: nosniff
< x-frame-options: SAMEORIGIN
< server: falcon/0.18.5
< date: Fri, 10 Aug 2018 16:24:59 GMT
< content-length: 11
< 
* Connection #0 to host localhost left intact
hello world
```

@tarcieri any thoughts?

**Comment by ioquatix** [comment]
I guess that means that I might be setting up the server SSL context incorrectly. I don't think I'm doing anything strange though: https://github.com/socketry/localhost/blob/de8964b6fe639e6638089095ec802ac26a8e7b14/lib/localhost/authority.rb#L105-L114

@tarcieri if you have any ideas it would be most appreciated/welcome.

**Comment by ioquatix** [comment]
So, I'm keen to get to the bottom of this. So, I've expanded testing.

I've added explicit testing using `openssl s_client` and `curl` to the `localhost` gem.

https://travis-ci.com/socketry/localhost/builds/81598559

Strangely enough, so far, tests seems to be passing. So, I wonder if there is some other issue. I wondered if it was something to do with ALPN. Further investigation is required.

**Comment by ioquatix** [comment]
Okay, I found the issue. Calling `context.freeze` causes the context to fail in Ruby v2.3.x. I don't know why this is, but removing it has fixed the issue. So, I'll bundle this with the next update.

**Comment by ioquatix** [comment]
Can you tell me `OpenSSL::SSL::SSLContext::DEFAULT_PARAMS` on your failing Ruby?

**Comment by ioquatix** [comment]
I wonder if you have a gem which is modifying those defaults...

**Comment by ioquatix** [comment]
Okay, so I was able to reproduce the issue you mentioned above. I will try to find out why it is happening. It worked okay for me on Safari, but on chrome it states:

<img width="423" alt="screen shot 2018-08-19 at 12 22 17 pm" src="https://user-images.githubusercontent.com/30030/44305154-f336f380-a3ab-11e8-802e-187bd4309fe7.png">

**Comment by ioquatix** [comment]
So, the above was on Ruby 2.3.x, while this is what I get running on Ruby 2.5:

<img width="448" alt="image" src="https://user-images.githubusercontent.com/30030/44305180-6e98a500-a3ac-11e8-8cb3-3812867b462a.png">

I think there is something wrong with Ruby 2.3 OpenSSL.

**Comment by ioquatix** [comment]
Okay, I found how to solve the problem with Ruby 2.3 - you need to manually specify EDCH key callback. After doing this, I could avoid the security issue. I tried to make sane defaults for Ruby 2.3 and Ruby 2.4+.

Can you try `localhost v1.1.4`?

**Comment by sobrinho** [comment]
Now it worked but I'm seeing a deadlock quite frequently.

```
E, [2018-08-20T08:46:51.315121 #92870] ERROR -- : ThreadError: deadlock; recursive locking
        /Users/sobrinho/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/rack-1.4.7/lib/rack/lock.rb:14:in `lock'
        /Users/sobrinho/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/rack-1.4.7/lib/rack/lock.rb:14:in `call'
        /Users/sobrinho/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/actionpack-3.2.22.5/lib/action_dispatch/middleware/static.rb:83:in `call'
        /Users/sobrinho/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/sentry-raven-2.6.3/lib/raven/integrations/rack.rb:50:in `call'
        /Users/sobrinho/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/rack-cors-1.0.1/lib/rack/cors.rb:93:in `call'
        /Users/sobrinho/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/railties-3.2.22.5/lib/rails/engine.rb:484:in `call'
        /Users/sobrinho/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/railties-3.2.22.5/lib/rails/application.rb:231:in `call'
        /Users/sobrinho/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/railties-3.2.22.5/lib/rails/railtie/configurable.rb:30:in `method_missing'
        /Users/sobrinho/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/falcon-0.18.5/lib/falcon/adapters/rack.rb:102:in `call'
        /Users/sobrinho/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/async-http-0.30.3/lib/async/http/middleware.rb:53:in `call'
        /Users/sobrinho/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/falcon-0.18.5/lib/falcon/adapters/rewindable.rb:59:in `call'
        /Users/sobrinho/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/async-http-0.30.3/lib/async/http/middleware.rb:53:in `call'
        /Users/sobrinho/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/async-http-0.30.3/lib/async/http/content_encoding.rb:44:in `call'
        /Users/sobrinho/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/async-http-0.30.3/lib/async/http/middleware.rb:53:in `call'
        /Users/sobrinho/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/async-http-0.30.3/lib/async/http/server.rb:54:in `block in accept'
        /Users/sobrinho/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/async-http-0.30.3/lib/async/http/protocol/http2/server.rb:56:in `receive_requests'
        /Users/sobrinho/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/async-http-0.30.3/lib/async/http/server.rb:49:in `accept'
        /Users/sobrinho/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/async-io-1.15.4/lib/async/io/socket.rb:62:in `block in accept_each'
        /Users/sobrinho/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/async-io-1.15.4/lib/async/io/ssl_socket.rb:124:in `block in accept'
        /Users/sobrinho/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/async-1.10.2/lib/async/task.rb:74:in `block in initialize'
```

**Comment by ioquatix** [comment]
Good, progress.

The lock issue I’ve seen before somewhere. It’s to do with unnecessary lock middleware trying to serialise access.

**Comment by sobrinho** [comment]
Well, this is a Rails 3.2 application, I do have the `config.threadsafe!` but only for the production environment.

I may have unexpected behavior enabling it for development mode, no?

**Comment by ioquatix** [comment]
It should be fine for development afaik, but perhaps try it and report back if you have issues.

**Comment by ioquatix** [comment]
For older apps it looks like you should manually specify it. It’s absolutely necessary for http/2 since it multiplexes connections by default.
