### ISSUE TITLE
Strange host name error

### ISSUE THREAD

**Issue by ioquatix** [socketry/falcon#134]
```
GET https://programming.dojo.net.nzprogramming.dojo.net.nz

request.ip: "::ffff:93.124.60.35"
request.referrer: nil
request.path: "programming.dojo.net.nz"
request.user_agent: "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"

HTTP_UPGRADE_INSECURE_REQUESTS: "1"
HTTP_USER_AGENT: "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"
HTTP_DNT: "1"
HTTP_ACCEPT: "*/*"
HTTP_ACCEPT_ENCODING: "deflate"
HTTP_ACCEPT_LANGUAGE: "ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7"
HTTP_X_FORWARDED_FOR: "::ffff:93.124.60.35"
HTTP_X_FORWARDED_PROTO: "https"
HTTP_FORWARDED: "for=::ffff:93.124.60.35;proto=https"
HTTP_VIA: "HTTP/1.0 Falcon::Middleware::Proxy"
HTTP_HOST: "programming.dojo.net.nz"

Exception ArgumentError: Invalid request path programming.dojo.net.nz
/srv/http/vendor/bundle/ruby/2.7.0/gems/utopia-2.13.3/lib/utopia/controller.rb:126:in `invoke_controllers'
/srv/http/vendor/bundle/ruby/2.7.0/gems/utopia-2.13.3/lib/utopia/controller.rb:163:in `call'
/srv/http/vendor/bundle/ruby/2.7.0/gems/utopia-2.13.3/lib/utopia/redirection.rb:64:in `call'
/srv/http/vendor/bundle/ruby/2.7.0/gems/utopia-2.13.3/lib/utopia/redirection.rb:130:in `call'
/srv/http/vendor/bundle/ruby/2.7.0/gems/utopia-2.13.3/lib/utopia/redirection.rb:130:in `call'
/srv/http/vendor/bundle/ruby/2.7.0/gems/utopia-2.13.3/lib/utopia/static.rb:104:in `call'
/srv/http/vendor/bundle/ruby/2.7.0/gems/utopia-2.13.3/lib/utopia/exceptions/mailer.rb:69:in `call'
/srv/http/vendor/bundle/ruby/2.7.0/gems/utopia-2.13.3/lib/utopia/exceptions/handler.rb:60:in `call'
/srv/http/vendor/bundle/ruby/2.7.0/gems/falcon-0.35.6/lib/falcon/adapters/rack.rb:183:in `call'
/srv/http/vendor/bundle/ruby/2.7.0/gems/protocol-http-0.14.4/lib/protocol/http/middleware.rb:42:in `call'
/srv/http/vendor/bundle/ruby/2.7.0/gems/falcon-0.35.6/lib/falcon/adapters/rewindable.rb:63:in `call'
/srv/http/vendor/bundle/ruby/2.7.0/gems/protocol-http-0.14.4/lib/protocol/http/middleware.rb:42:in `call'
/srv/http/vendor/bundle/ruby/2.7.0/gems/protocol-http-0.14.4/lib/protocol/http/content_encoding.rb:46:in `call'
/srv/http/vendor/bundle/ruby/2.7.0/gems/protocol-http-0.14.4/lib/protocol/http/middleware.rb:42:in `call'
/srv/http/vendor/bundle/ruby/2.7.0/gems/async-http-0.50.6/lib/async/http/server.rb:64:in `block in accept'
/srv/http/vendor/bundle/ruby/2.7.0/gems/async-http-0.50.6/lib/async/http/protocol/http2/server.rb:73:in `block in each'
/srv/http/vendor/bundle/ruby/2.7.0/gems/async-1.24.2/lib/async/task.rb:258:in `block in make_fiber'
```

**Comment by olleolleolle** [comment]
Here's me reading the backtrace, and thinking out loud.

Oh, so the HTTP_HOST: `programming.dojo.net.nz` and the HTTP_X_FORWARDED_PROTO `https`, if we use those to subtract from the GET value:

Like `"https://programming.dojo.net.nzprogramming.dojo.net.nz"` - `"https://programming.dojo.net.nz"`... which would leave the "request path" `programming.dojo.net.nz`.

**Comment by ioquatix** [comment]
Yes, and it always seems to be the same user agent and `HTTP_ACCEPT_LANGUAGE` from Russia.

I don't think this is a bug with Falcon, but I'll try to reproduce it in the parser to see if it's possible. It literally looks like a request:

```
GET programming.dojo.net.nz
Host:  programming.dojo.net.nz
```

**Comment by ioquatix** [comment]
Hitting my own server with this produces the exact same error:

```
#!/usr/bin/env ruby

require 'async'
require 'async/http/endpoint'
require 'async/http/client'

Async do
	endpoint = Async::HTTP::Endpoint.parse("https://programming.dojo.net.nz")
	client = Async::HTTP::Client.new(endpoint)
	
	response = client.get("programming.dojo.net.nz")
	puts response, response.read
end
```

Results in:

```
GET https://programming.dojo.net.nzprogramming.dojo.net.nz

request.ip: "2406:e003:1ce6:7d01:e440:fdcf:63a1:16a"
request.referrer: nil
request.path: "programming.dojo.net.nz"
request.user_agent: nil

HTTP_X_FORWARDED_FOR: "2406:e003:1ce6:7d01:e440:fdcf:63a1:16a"
HTTP_X_FORWARDED_PROTO: "https"
HTTP_FORWARDED: "for=2406:e003:1ce6:7d01:e440:fdcf:63a1:16a;proto=https"
HTTP_VIA: "h2 Falcon::Middleware::Proxy"
HTTP_HOST: "programming.dojo.net.nz"

Exception ArgumentError: Invalid request path programming.dojo.net.nz
/srv/http/vendor/bundle/ruby/2.7.0/gems/utopia-2.13.3/lib/utopia/controller.rb:126:in `invoke_controllers'
/srv/http/vendor/bundle/ruby/2.7.0/gems/utopia-2.13.3/lib/utopia/controller.rb:163:in `call'
/srv/http/vendor/bundle/ruby/2.7.0/gems/utopia-2.13.3/lib/utopia/redirection.rb:64:in `call'
/srv/http/vendor/bundle/ruby/2.7.0/gems/utopia-2.13.3/lib/utopia/redirection.rb:130:in `call'
/srv/http/vendor/bundle/ruby/2.7.0/gems/utopia-2.13.3/lib/utopia/redirection.rb:130:in `call'
/srv/http/vendor/bundle/ruby/2.7.0/gems/utopia-2.13.3/lib/utopia/static.rb:104:in `call'
/srv/http/vendor/bundle/ruby/2.7.0/gems/utopia-2.13.3/lib/utopia/exceptions/mailer.rb:69:in `call'
/srv/http/vendor/bundle/ruby/2.7.0/gems/utopia-2.13.3/lib/utopia/exceptions/handler.rb:60:in `call'
/srv/http/vendor/bundle/ruby/2.7.0/gems/falcon-0.35.6/lib/falcon/adapters/rack.rb:183:in `call'
/srv/http/vendor/bundle/ruby/2.7.0/gems/protocol-http-0.14.4/lib/protocol/http/middleware.rb:42:in `call'
/srv/http/vendor/bundle/ruby/2.7.0/gems/falcon-0.35.6/lib/falcon/adapters/rewindable.rb:63:in `call'
/srv/http/vendor/bundle/ruby/2.7.0/gems/protocol-http-0.14.4/lib/protocol/http/middleware.rb:42:in `call'
/srv/http/vendor/bundle/ruby/2.7.0/gems/protocol-http-0.14.4/lib/protocol/http/content_encoding.rb:46:in `call'
/srv/http/vendor/bundle/ruby/2.7.0/gems/protocol-http-0.14.4/lib/protocol/http/middleware.rb:42:in `call'
/srv/http/vendor/bundle/ruby/2.7.0/gems/async-http-0.50.6/lib/async/http/server.rb:64:in `block in accept'
/srv/http/vendor/bundle/ruby/2.7.0/gems/async-http-0.50.6/lib/async/http/protocol/http2/server.rb:73:in `block in each'
/srv/http/vendor/bundle/ruby/2.7.0/gems/async-1.24.2/lib/async/task.rb:258:in `block in make_fiber'
```

**Comment by ioquatix** [comment]
After reviewing this, I'm confident this is a problem in the request, not the parser or server itself.
