### ISSUE TITLE
Rack::Lint::LintError: rack.input #<Falcon::Adapters::Input:0x000055a9b437cbd0> does not respond to #rewind

### ISSUE THREAD

**Issue by strzibny** [socketry/falcon#14]
Sorry for kind of combining two issues. I can overcome the first by putting falcon into Gemfile, but then I get a weird error.

First I tried to run falcon as:

```
$ gem install falcon
$ falcon serve
WARN: Unresolved specs during Gem::Specification.reset:
      rake (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/home/strzibny/.gem/ruby/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require': cannot load such file -- async/container/forked (LoadError)
	from /home/strzibny/.gem/ruby/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
	from /home/strzibny/.gem/ruby/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
	from /home/strzibny/.gem/ruby/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
	from /home/strzibny/.gem/ruby/gems/falcon-0.18.4/lib/falcon/command/serve.rb:60:in `container_class'
	from /home/strzibny/.gem/ruby/gems/falcon-0.18.4/lib/falcon/command/serve.rb:80:in `run'
	from /home/strzibny/.gem/ruby/gems/falcon-0.18.4/lib/falcon/command/serve.rb:103:in `invoke'
	from /home/strzibny/.gem/ruby/gems/falcon-0.18.4/lib/falcon/command.rb:68:in `invoke'
	from /home/strzibny/.gem/ruby/gems/falcon-0.18.4/bin/falcon:26:in `<top (required)>'
	from /home/strzibny/bin/falcon:23:in `load'
	from /home/strzibny/bin/falcon:23:in `<main>'
[strzibny@strzibny benchmark-app]$ RACK_HANDLER=falcon rails server
Exiting
/home/strzibny/.gem/ruby/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require': cannot load such file -- rack/handler/falcon (LoadError)
	from /home/strzibny/.gem/ruby/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
	from /home/strzibny/.gem/ruby/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
	from /home/strzibny/.gem/ruby/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
	from /home/strzibny/.gem/ruby/gems/rack-2.0.5/lib/rack/handler.rb:74:in `try_require'
	from /home/strzibny/.gem/ruby/gems/rack-2.0.5/lib/rack/handler.rb:16:in `get'
	from /home/strzibny/.gem/ruby/gems/rack-2.0.5/lib/rack/handler.rb:53:in `default'
	from /home/strzibny/.gem/ruby/gems/rack-2.0.5/lib/rack/server.rb:304:in `server'
	from /home/strzibny/.gem/ruby/gems/railties-5.2.0/lib/rails/commands/server/server_command.rb:105:in `use_puma?'
	from /home/strzibny/.gem/ruby/gems/railties-5.2.0/lib/rails/commands/server/server_command.rb:76:in `print_boot_information'
	from /home/strzibny/.gem/ruby/gems/railties-5.2.0/lib/rails/commands/server/server_command.rb:47:in `start'
	from /home/strzibny/.gem/ruby/gems/railties-5.2.0/lib/rails/commands/server/server_command.rb:147:in `block in perform'
	from /home/strzibny/.gem/ruby/gems/railties-5.2.0/lib/rails/commands/server/server_command.rb:142:in `tap'
	from /home/strzibny/.gem/ruby/gems/railties-5.2.0/lib/rails/commands/server/server_command.rb:142:in `perform'
	from /home/strzibny/.gem/ruby/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /home/strzibny/.gem/ruby/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/strzibny/.gem/ruby/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /home/strzibny/.gem/ruby/gems/railties-5.2.0/lib/rails/command/base.rb:65:in `perform'
	from /home/strzibny/.gem/ruby/gems/railties-5.2.0/lib/rails/command.rb:46:in `invoke'
	from /home/strzibny/.gem/ruby/gems/railties-5.2.0/lib/rails/commands.rb:18:in `<main>'
	from /home/strzibny/.gem/ruby/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	from /home/strzibny/.gem/ruby/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from /home/strzibny/.gem/ruby/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	from /home/strzibny/.gem/ruby/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from /home/strzibny/.gem/ruby/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	from /home/strzibny/.gem/ruby/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
	from /home/strzibny/.gem/ruby/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
	from /home/strzibny/.gem/ruby/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
	from /home/strzibny/Projects/benchmark-app/bin/rails:9:in `<top (required)>'
	from /home/strzibny/.gem/ruby/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
	from /home/strzibny/.gem/ruby/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
	from /home/strzibny/.gem/ruby/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
	from /home/strzibny/.gem/ruby/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
	from /home/strzibny/.gem/ruby/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
	from /home/strzibny/.gem/ruby/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
	from /home/strzibny/.gem/ruby/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/strzibny/Projects/benchmark-app/bin/spring:15:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'

```
This does not work. Luckily adding it to Gemfile helped:
```
$ bundle exec rackup -s falcon -r falcon
Rack::Lint::LintError: rack.input #<Falcon::Adapters::Input:0x000055a9b437cbd0> does not respond to #rewind
	/home/strzibny/.gem/ruby/gems/rack-2.0.5/lib/rack/lint.rb:20:in `assert'
	/home/strzibny/.gem/ruby/gems/rack-2.0.5/lib/rack/lint.rb:347:in `block in check_input'
	/home/strzibny/.gem/ruby/gems/rack-2.0.5/lib/rack/lint.rb:346:in `each'
	/home/strzibny/.gem/ruby/gems/rack-2.0.5/lib/rack/lint.rb:346:in `check_input'
	/home/strzibny/.gem/ruby/gems/rack-2.0.5/lib/rack/lint.rb:291:in `check_env'
	/home/strzibny/.gem/ruby/gems/rack-2.0.5/lib/rack/lint.rb:43:in `_call'
	/home/strzibny/.gem/ruby/gems/rack-2.0.5/lib/rack/lint.rb:37:in `call'
	/home/strzibny/.gem/ruby/gems/rack-2.0.5/lib/rack/show_exceptions.rb:23:in `call'
	/home/strzibny/.gem/ruby/gems/rack-2.0.5/lib/rack/common_logger.rb:33:in `call'
	/home/strzibny/.gem/ruby/gems/rack-2.0.5/lib/rack/chunked.rb:54:in `call'
	/home/strzibny/.gem/ruby/gems/rack-2.0.5/lib/rack/content_length.rb:15:in `call'
	/home/strzibny/.gem/ruby/gems/falcon-0.18.4/lib/falcon/adapters/rack.rb:102:in `call'
	/home/strzibny/.gem/ruby/gems/async-http-0.30.3/lib/async/http/middleware.rb:53:in `call'
	/home/strzibny/.gem/ruby/gems/falcon-0.18.4/lib/falcon/adapters/rewindable.rb:59:in `call'
	/home/strzibny/.gem/ruby/gems/async-http-0.30.3/lib/async/http/middleware.rb:53:in `call'
	/home/strzibny/.gem/ruby/gems/async-http-0.30.3/lib/async/http/server.rb:54:in `block in accept'
	/home/strzibny/.gem/ruby/gems/async-http-0.30.3/lib/async/http/protocol/http11.rb:134:in `receive_requests'
	/home/strzibny/.gem/ruby/gems/async-http-0.30.3/lib/async/http/protocol/http1.rb:59:in `receive_requests'
	/home/strzibny/.gem/ruby/gems/async-http-0.30.3/lib/async/http/server.rb:49:in `accept'
	/home/strzibny/.gem/ruby/gems/async-io-1.15.2/lib/async/io/socket.rb:62:in `block in accept_each'
	/home/strzibny/.gem/ruby/gems/async-io-1.15.2/lib/async/io/socket.rb:95:in `block in accept'
	/home/strzibny/.gem/ruby/gems/async-1.10.1/lib/async/task.rb:74:in `block in initialize'


```

**Comment by ioquatix** [comment]
The first problem is to be expected, the way it's currently set up in rails, you need to add the gem to your gem file to install all dependencies.

The second issue is more interesting. I will need to investigate.

**Comment by ioquatix** [comment]
So, `falcon serve` is the preferred method for starting a server.

`RACK_HANDLER=falcon rails server` works but is limited to using the rack handler, which only starts one thread.

`bundle exec rackup -s falcon -r falcon` is essentially the same as the above.

I've pushed a fix for the lint error, I hope to release soon `v0.18.6`.

**Comment by strzibny** [comment]
Thanks. I mentioned the first one mainly because it confused me in README with *Or install it yourself as: gem install falcon*. I will try it again once new version is out.

**Comment by ioquatix** [comment]
Yeah, I can see how that is confusing. To use it with rails you must follow the instructions here: https://github.com/socketry/falcon#integration-with-rails

Falcon can be used with any rack-compatible stack so those are general instructions for how to integrate it, but I will try to improve that.

**Comment by ioquatix** [comment]
Okay, this was fixed in 0e9e84d4847ce6179fc0fe57ba997973284b2c69 and released in `v0.18.5`. I'll work on the documentation separately, but if you could try it out and let me know what would be great.

**Comment by strzibny** [comment]
Cool, just tried and it works!

**Comment by ioquatix** [comment]
Thanks for your feedback!
