### ISSUE TITLE
JRuby test helper fails with NoMethodError:   undefined method `memsize_of' for ObjectSpace:Module

### ISSUE THREAD

**Issue by olleolleolle** [socketry/falcon#175]
The JRuby test matrix element fails with this message: sort of before it even got started.

Reported that issue in its project: https://github.com/socketry/rspec-memory/issues/8

```
An error occurred while loading spec_helper.
Failure/Error: require "async/rspec"

NoMethodError:
  undefined method `memsize_of' for ObjectSpace:Module
# ./vendor/bundle/jruby/2.6.0/gems/rspec-memory-1.0.3/lib/rspec/memory/trace.rb:26:in `block in Memory'
# ./vendor/bundle/jruby/2.6.0/gems/rspec-memory-1.0.3/lib/rspec/memory/trace.rb:25:in `<module:Memory>'
# ./vendor/bundle/jruby/2.6.0/gems/rspec-memory-1.0.3/lib/rspec/memory/trace.rb:24:in `<module:RSpec>'
# ./vendor/bundle/jruby/2.6.0/gems/rspec-memory-1.0.3/lib/rspec/memory/trace.rb:23:in `<main>'
# ./vendor/bundle/jruby/2.6.0/gems/rspec-memory-1.0.3/lib/rspec/memory/matchers/limit_allocations.rb:22:in `<main>'
# ./vendor/bundle/jruby/2.6.0/gems/rspec-memory-1.0.3/lib/rspec/memory.rb:21:in `<main>'
# ./vendor/bundle/jruby/2.6.0/gems/async-rspec-1.16.1/lib/async/rspec/memory.rb:21:in `<main>'
# ./vendor/bundle/jruby/2.6.0/gems/async-rspec-1.16.1/lib/async/rspec.rb:23:in `<main>'
# ./spec/spec_helper.rb:6:in `<main>'
No examples found.
No examples found.
```

**Comment by ioquatix** [comment]
The main issue right now is the `io-event` gem does not support JRuby. I hope we can address that soon. I don't believe we are using `rspec-memory` in the falcon test suite any more.

**Comment by olleolleolle** [comment]
Thanks for keeping the Issue tracker tidy!
