### ISSUE TITLE
async-io still in use

### ISSUE THREAD

**Issue by jakeonfire** [socketry/falcon#238]
https://github.com/socketry/falcon/blob/2379de9da42ff9bdad4eff6556fb4c57230585b7/lib/falcon/proxy_endpoint.rb#L6-L10

starting the server with rack environment results in:
```
<internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require': cannot load such file -- async/io/unix_endpoint (LoadError)
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /usr/local/bundle/gems/falcon-0.47.0/lib/falcon/proxy_endpoint.rb:6:in `<top (required)>'
	from /usr/local/bundle/gems/falcon-0.47.0/lib/falcon/environment/application.rb:8:in `require_relative'
	from /usr/local/bundle/gems/falcon-0.47.0/lib/falcon/environment/application.rb:8:in `<top (required)>'
	from /usr/local/bundle/gems/falcon-0.47.0/lib/falcon/environment/rack.rb:6:in `require_relative'
	from /usr/local/bundle/gems/falcon-0.47.0/lib/falcon/environment/rack.rb:6:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /app/falcon.rb:2:in `load_file'
	from /usr/local/bundle/gems/async-service-0.12.0/lib/async/service/loader.rb:38:in `instance_eval'
	from /usr/local/bundle/gems/async-service-0.12.0/lib/async/service/loader.rb:38:in `load_file'
	from /usr/local/bundle/gems/falcon-0.47.0/lib/falcon/configuration.rb:31:in `load_file'
	from /usr/local/bundle/gems/falcon-0.47.0/lib/falcon/command/paths.rb:27:in `block in configuration'
	from /usr/local/bundle/gems/falcon-0.47.0/lib/falcon/command/paths.rb:24:in `each'
	from /usr/local/bundle/gems/falcon-0.47.0/lib/falcon/command/paths.rb:24:in `each'
	from /usr/local/bundle/gems/falcon-0.47.0/lib/falcon/command/paths.rb:24:in `configuration'
	from /usr/local/bundle/gems/falcon-0.47.0/lib/falcon/command/host.rb:41:in `call'
	from /usr/local/bundle/gems/samovar-2.3.0/lib/samovar/command.rb:21:in `call'
	from /usr/local/bundle/gems/falcon-0.47.0/bin/falcon-host:26:in `<top (required)>'
	from /app/bin/falcon-host:27:in `load'
	from /app/bin/falcon-host:27:in `<main>'
```

our `falcon.rb:2` has: `require "falcon/environment/rack"`

**Comment by jakeonfire** [comment]
in fact, searching for `async/io` yields 7 results 🤔

**Comment by ioquatix** [comment]
Oops, I'll fix it :)
