### ISSUE TITLE
Falcon is tryng to make me authenticate using X.509 User certificate

### ISSUE THREAD

**Issue by brodock** [socketry/falcon#24]
Probably because my browser advertises itself as having local X.509 certificate that can be used as a way to authenticate, I get the browser dialog requesting to select a certificate to authenticate with.

There is probably a flag on the backend that needs to be toggled to not do that.

When I selected one of the existing certificates, this was the output from the terminal:

```
E, [2018-10-22T18:13:39.339422 #92506] ERROR -- #<Async::IO::SSLServer:0x0000000123a8ca40>: SSL_accept returned=1 errno=0 state=error: sslv3 alert bad certificate (OpenSSL::SSL::SSLError)
/Users/brodock/.rvm/gems/ruby-2.4.4/gems/async-io-1.16.1/lib/async/io/generic.rb:128:in `accept_nonblock'
/Users/brodock/.rvm/gems/ruby-2.4.4/gems/async-io-1.16.1/lib/async/io/generic.rb:128:in `async_send'
/Users/brodock/.rvm/gems/ruby-2.4.4/gems/async-io-1.16.1/lib/async/io/generic.rb:47:in `block in wrap_blocking_method'
/Users/brodock/.rvm/gems/ruby-2.4.4/gems/async-io-1.16.1/lib/async/io/ssl_socket.rb:122:in `block in accept'
/Users/brodock/.rvm/gems/ruby-2.4.4/gems/async-1.10.3/lib/async/task.rb:74:in `block in initialize'
```

**Comment by brodock** [comment]
Yes

**Comment by georgerb** [comment]
> Yes

Then you can instruct Rails to pick up Falcon as your Rack handler:

export RACK_HANDLER=falcon

and then run as normally you do with your dev server:

rails s

Or altogetther:
RACK_HANDLER=falcon rails s

**Comment by ioquatix** [comment]
Interesting.

Frankly, my knowledge about how browsers and servers should work with self-signed certificates is all by trial-and-error. I found that the variety of browsers doing different things made it quite hard to get one approach to work consistently.

I actually don't know what could be causing the problem you have.

- What browser are you using?
- How do you set up a "local X.509 certificate that can be used as a way to authenticate"?
- If you remove your local certificates as described above, does it work as expected?

The [localhost](https://github.com/socketry/localhost) gem responsible for the self-signed certificates. So, it probably requires a fix there.

**Comment by brodock** [comment]
@georgerb I was running that way already... I also followed the discussion in the rack issue about making it one of the default handlers etc, the issue is a little different.

**Comment by georgerb** [comment]
> @georgerb I was running that way already... I also followed the discussion in the rack issue about making it one of the default handlers etc, the issue is a little different.
Sorry, my bad.

**Comment by brodock** [comment]
@ioquatix I tried with firefox, and I'm not 100% sure how I got this certificate set-up, I think this is the one I use to sign ruby so I don't have to trust it everytime I run any server.

**Comment by ioquatix** [comment]
I'm not sure if this helps me or not, but can you give me the following:

- Ruby version
- OpenSSL library version:
```
OpenSSL::OPENSSL_LIBRARY_VERSION                                                                                                                      
=> "OpenSSL 1.0.2p  14 Aug 2018"
```
- Ciphers in use
```
[6] pry(main)> require 'localhost/authority'                                                                                                                         
=> true
[7] pry(main)> Localhost::Authority.new.server_context.ciphers                                                                                                       
=> [["ECDHE-RSA-AES128-GCM-SHA256", "TLSv1/SSLv3", 128, 128],
 ["ECDHE-ECDSA-AES128-GCM-SHA256", "TLSv1/SSLv3", 128, 128],
 ["ECDHE-RSA-AES128-SHA256", "TLSv1/SSLv3", 128, 128],
 ["ECDHE-ECDSA-AES128-SHA256", "TLSv1/SSLv3", 128, 128],
 ["ECDHE-RSA-AES128-SHA", "TLSv1/SSLv3", 128, 128],
 ["ECDHE-ECDSA-AES128-SHA", "TLSv1/SSLv3", 128, 128],
 ["AES128-GCM-SHA256", "TLSv1/SSLv3", 128, 128],
 ["AES128-SHA256", "TLSv1/SSLv3", 128, 128],
 ["AES128-SHA", "TLSv1/SSLv3", 128, 128],
 ["ECDHE-RSA-AES256-GCM-SHA384", "TLSv1/SSLv3", 256, 256],
 ["ECDHE-ECDSA-AES256-GCM-SHA384", "TLSv1/SSLv3", 256, 256],
 ["ECDHE-RSA-AES256-SHA384", "TLSv1/SSLv3", 256, 256],
 ["ECDHE-ECDSA-AES256-SHA384", "TLSv1/SSLv3", 256, 256],
 ["ECDHE-RSA-AES256-SHA", "TLSv1/SSLv3", 256, 256],
 ["ECDHE-ECDSA-AES256-SHA", "TLSv1/SSLv3", 256, 256],
 ["AES256-GCM-SHA384", "TLSv1/SSLv3", 256, 256],
 ["AES256-SHA256", "TLSv1/SSLv3", 256, 256],
 ["AES256-SHA", "TLSv1/SSLv3", 256, 256],
 ["ECDHE-RSA-DES-CBC3-SHA", "TLSv1/SSLv3", 112, 168],
 ["ECDHE-ECDSA-DES-CBC3-SHA", "TLSv1/SSLv3", 112, 168],
 ["DES-CBC3-SHA", "TLSv1/SSLv3", 112, 168]]
```

Thanks.

**Comment by ioquatix** [comment]
Also, do you mind attaching some screenshots of what Firefox is actually doing? Because I don't completely know what's going on here.

**Comment by xtagon** [comment]
I experience the same issue. Running with the RACK_HANDLER works, but then how do you pass options (like thread/process counts) through to Falcon?

**Comment by ioquatix** [comment]
You can't pass any options because it's so limited to start it like that. Better just to use `falcon serve`.

Do you mind sharing some screenshots of exactly what the browser is doing?

**Comment by xtagon** [comment]
![image](https://user-images.githubusercontent.com/47229/47468075-36e41a00-d7ae-11e8-89b7-573564937346.png)

This is from running `falcon serve -p 5100` (I can't use 9292, but that's all I did differently)

**Comment by xtagon** [comment]
And here is what the logs kept repeating after requesting the page:

```
E, [2018-10-24T16:58:40.660072 #24337] ERROR -- #<Async::IO::SSLServer:0x000055af56af4960>: SSL_accept returned=1 errno=0 state=SSLv2/v3 read client hello A: http request (OpenSSL::SSL::SSLError)
/home/xtagon/.asdf/installs/ruby/2.4.4/lib/ruby/gems/2.4.0/gems/async-io-1.16.1/lib/async/io/generic.rb:128:in `accept_nonblock'
/home/xtagon/.asdf/installs/ruby/2.4.4/lib/ruby/gems/2.4.0/gems/async-io-1.16.1/lib/async/io/generic.rb:128:in `async_send'
/home/xtagon/.asdf/installs/ruby/2.4.4/lib/ruby/gems/2.4.0/gems/async-io-1.16.1/lib/async/io/generic.rb:47:in `block in wrap_blocking_method'
/home/xtagon/.asdf/installs/ruby/2.4.4/lib/ruby/gems/2.4.0/gems/async-io-1.16.1/lib/async/io/ssl_socket.rb:122:in `block in accept'
/home/xtagon/.asdf/installs/ruby/2.4.4/lib/ruby/gems/2.4.0/gems/async-1.10.3/lib/async/task.rb:74:in `block in initialize'
```

**Comment by ioquatix** [comment]
Try using `https://localhost:5100`

**Comment by xtagon** [comment]
That gives me this:

![image](https://user-images.githubusercontent.com/47229/47468133-8591b400-d7ae-11e8-87c1-fd27d9df8eea.png)

Then when I go to Advanced, I can add a security exception, and then my app will load. However, if I do that, I cannot sign into my Rails application because Devise has an invalid authenticity token error. The error does not happen when I run with Puma.

**Comment by ioquatix** [comment]
Right. So the issue you are having is actually not the one reported here.

You will need to add an exception to support `https` for localhost as no browser currently provides any easy way to do this. This isn't a problem with Puma as it doesn't support `https`.

If you don't want to use https, simply run `falcon serve --bind http://localhost:5100`.

Please feel free to file a new issue regarding Devise. That seems like something entirely different.

**Comment by xtagon** [comment]
Got it. Thank you very much for you help!

**Comment by xtagon** [comment]
When I do the HTTP bind you suggested, Devise no longer throws the invalid authenticity token exception. That's good enough for me but I'll open a new issue if it happens in a production environment where HTTPS will be necessary. Thanks again for your support.

**Comment by ioquatix** [comment]
Please open a new issue :)

**Comment by brodock** [comment]
```
=> "OpenSSL 1.1.1  11 Sep 2018"

**Comment by brodock** [comment]
<img width="1552" alt="certificate request" src="https://user-images.githubusercontent.com/20575/47606235-56c74800-da11-11e8-8ae8-6e734f9c55f1.png">

**Comment by ioquatix** [comment]
Thanks, I will try this with Firefox at my earliest convenience and see if I can reproduce.

**Comment by turboladen** [comment]
FWIW, I tried taking falcon for a spin with one of the Rails apps in our stack at work. We rely on haproxy to forward requests to the appropriate backend, so I'm guessing my results are probably related to that. If I `falcon serve -p 3456` I get this (without ever making a request; these are all from haproxy using my current settings):

```
E, [2018-11-29T11:28:28.852141 #42727] ERROR -- #<Async::IO::SSLServer:0x00007ff1314984d0>: Connection reset by peer - SSL_accept (Errno::ECONNRESET)
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-io-1.16.4/lib/async/io/generic.rb:128:in `accept_nonblock'
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-io-1.16.4/lib/async/io/generic.rb:128:in `async_send'
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-io-1.16.4/lib/async/io/generic.rb:47:in `block in wrap_blocking_method'
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-io-1.16.4/lib/async/io/ssl_socket.rb:126:in `block in accept'
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-1.11.0/lib/async/task.rb:74:in `block in initialize'
E, [2018-11-29T11:28:30.854848 #42731] ERROR -- #<Async::IO::SSLServer:0x00007ff12dbf3da0>: Connection reset by peer - SSL_accept (Errno::ECONNRESET)
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-io-1.16.4/lib/async/io/generic.rb:128:in `accept_nonblock'
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-io-1.16.4/lib/async/io/generic.rb:128:in `async_send'
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-io-1.16.4/lib/async/io/generic.rb:47:in `block in wrap_blocking_method'
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-io-1.16.4/lib/async/io/ssl_socket.rb:126:in `block in accept'
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-1.11.0/lib/async/task.rb:74:in `block in initialize'
E, [2018-11-29T11:28:32.861120 #42732] ERROR -- #<Async::IO::SSLServer:0x00007ff12dbf3da0>: Connection reset by peer - SSL_accept (Errno::ECONNRESET)
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-io-1.16.4/lib/async/io/generic.rb:128:in `accept_nonblock'
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-io-1.16.4/lib/async/io/generic.rb:128:in `async_send'
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-io-1.16.4/lib/async/io/generic.rb:47:in `block in wrap_blocking_method'
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-io-1.16.4/lib/async/io/ssl_socket.rb:126:in `block in accept'
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-1.11.0/lib/async/task.rb:74:in `block in initialize'
E, [2018-11-29T11:28:34.865432 #42730] ERROR -- #<Async::IO::SSLServer:0x00007ff12dc2c380>: Connection reset by peer - SSL_accept (Errno::ECONNRESET)
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-io-1.16.4/lib/async/io/generic.rb:128:in `accept_nonblock'
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-io-1.16.4/lib/async/io/generic.rb:128:in `async_send'
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-io-1.16.4/lib/async/io/generic.rb:47:in `block in wrap_blocking_method'
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-io-1.16.4/lib/async/io/ssl_socket.rb:126:in `block in accept'
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-1.11.0/lib/async/task.rb:74:in `block in initialize'
```

If I go the `RACK_HANDLER=falcon rails s` route, I get this:

```
E, [2018-11-29T11:27:54.794671 #32832] ERROR -- #<Async::IO::Socket:0x00007fdd5616b8a0>: Invalid argument - setsockopt(2) (Errno::EINVAL)
/Users/sloveless/.rubies/ruby-2.5.3/lib/ruby/2.5.0/forwardable.rb:229:in `setsockopt'
/Users/sloveless/.rubies/ruby-2.5.3/lib/ruby/2.5.0/forwardable.rb:229:in `setsockopt'
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-http-0.37.4/lib/async/http/server.rb:45:in `accept'
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-io-1.16.4/lib/async/io/socket.rb:68:in `block in accept_each'
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-io-1.16.4/lib/async/io/socket.rb:101:in `block in accept'
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-1.11.0/lib/async/task.rb:74:in `block in initialize'
E, [2018-11-29T11:27:58.801719 #32832] ERROR -- #<Async::IO::Socket:0x00007fdd5616b8a0>: Invalid argument - setsockopt(2) (Errno::EINVAL)
/Users/sloveless/.rubies/ruby-2.5.3/lib/ruby/2.5.0/forwardable.rb:229:in `setsockopt'
/Users/sloveless/.rubies/ruby-2.5.3/lib/ruby/2.5.0/forwardable.rb:229:in `setsockopt'
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-http-0.37.4/lib/async/http/server.rb:45:in `accept'
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-io-1.16.4/lib/async/io/socket.rb:68:in `block in accept_each'
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-io-1.16.4/lib/async/io/socket.rb:101:in `block in accept'
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-1.11.0/lib/async/task.rb:74:in `block in initialize'
E, [2018-11-29T11:28:00.804774 #32832] ERROR -- #<Async::IO::Socket:0x00007fdd5616b8a0>: Invalid argument - setsockopt(2) (Errno::EINVAL)
/Users/sloveless/.rubies/ruby-2.5.3/lib/ruby/2.5.0/forwardable.rb:229:in `setsockopt'
/Users/sloveless/.rubies/ruby-2.5.3/lib/ruby/2.5.0/forwardable.rb:229:in `setsockopt'
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-http-0.37.4/lib/async/http/server.rb:45:in `accept'
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-io-1.16.4/lib/async/io/socket.rb:68:in `block in accept_each'
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-io-1.16.4/lib/async/io/socket.rb:101:in `block in accept'
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-1.11.0/lib/async/task.rb:74:in `block in initialize'
E, [2018-11-29T11:28:04.810394 #32832] ERROR -- #<Async::IO::Socket:0x00007fdd5616b8a0>: Invalid argument - setsockopt(2) (Errno::EINVAL)
/Users/sloveless/.rubies/ruby-2.5.3/lib/ruby/2.5.0/forwardable.rb:229:in `setsockopt'
/Users/sloveless/.rubies/ruby-2.5.3/lib/ruby/2.5.0/forwardable.rb:229:in `setsockopt'
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-http-0.37.4/lib/async/http/server.rb:45:in `accept'
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-io-1.16.4/lib/async/io/socket.rb:68:in `block in accept_each'
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-io-1.16.4/lib/async/io/socket.rb:101:in `block in accept'
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-1.11.0/lib/async/task.rb:74:in `block in initialize'
```

...over and over again.

If I actually make a request from our frontend app, I see in the Network tab that responses are coming back, yet nothing ever gets rendered. If I switch back to puma, the frontend data gets rendered just fine. Certainly the rendering stuff wouldn't be falcon's fault, but the combination of a) the SSL errors, b) no normal Rails logs to the terminal, c) different behavior on my client just makes things seem a bit fishy. 

I'll keep using puma, but falcon seems interesting so I thought I'd post my results in case it helps anyone out.

**Comment by turboladen** [comment]
Ah, you know what... I still get the `Async` errors, but if I do `RACK_HANDLER=falcon rails s -p 3456`, things start behaving normally. It seems falcon is disregarding the changes to `Rails::Command::ServerCommand` that we have in `config/boot.rb`:

```
ENV['BUNDLE_GEMFILE'] ||= File.expand_path('../Gemfile', __dir__)

require 'bundler/setup' # Set up gems listed in the Gemfile.
require 'bootsnap/setup'
require 'rails/command'
require 'rails/commands/server/server_command'

class Rails::Command::ServerCommand
  class_option :port, aliases: '-p', type: :numeric,
                      desc: 'Runs Rails on the specified port.', banner: :port, default: 3456
end
```

We set the port in all of our apps like this so developers don't always have to manually add the flag.

**Comment by ioquatix** [comment]
@turboladen thanks for your report. This is almost certainly an entirely different issue from the one reported.

> If I falcon serve -p 3456 I get this (without ever making a request; these are all from haproxy using my current settings): `Connection reset by peer - SSL_accept`

Can you confirm you are connecting using `https`? Because this is what falcon is expecting. If you want to bind using `http`, please try `falcon serve --bind http://localhost:3456`.

> `Invalid argument - setsockopt(2) (Errno::EINVAL)`

This actually seems like a bug, so I'll try to figure it out.

**Comment by ioquatix** [comment]
@turboladen do you mind telling me what OS, version and Rails version you are using?

**Comment by turboladen** [comment]
> Can you confirm you are connecting using https?

Aah, no, not on development. That makes more sense. When I run the updated falcon command, it works, but I still get these suckers:

```
kraken git:feature/DEV-3593 ❯ bin/falcon --bind http://localhost:3456
W, [2018-11-29T17:14:41.923145 #41210]  WARN -- Skylight: [SKYLIGHT] [3.1.1] Running Skylight in development mode. No data will be reported until you deploy your app.
(To disable this message for all local apps, run `skylight disable_dev_warning`.)
I, [2018-11-29T17:14:43.623550 #41210]  INFO -- : Falcon taking flight! Binding to #<Falcon::Endpoint http://localhost:3456/ {}> [Async::Container::Forked with concurrency: 8]
I, [2018-11-29T17:14:43.628830 #41901]  INFO -- : Send `kill -USR1 41901` for detailed status :)
I, [2018-11-29T17:14:43.629755 #41902]  INFO -- : Send `kill -USR1 41902` for detailed status :)
I, [2018-11-29T17:14:43.630707 #41903]  INFO -- : Send `kill -USR1 41903` for detailed status :)
I, [2018-11-29T17:14:43.632478 #41904]  INFO -- : Send `kill -USR1 41904` for detailed status :)
I, [2018-11-29T17:14:43.634167 #41906]  INFO -- : Send `kill -USR1 41906` for detailed status :)
I, [2018-11-29T17:14:43.635761 #41908]  INFO -- : Send `kill -USR1 41908` for detailed status :)
I, [2018-11-29T17:14:43.636728 #41909]  INFO -- : Send `kill -USR1 41909` for detailed status :)
I, [2018-11-29T17:14:43.637630 #41910]  INFO -- : Send `kill -USR1 41910` for detailed status :)
E, [2018-11-29T17:14:44.116826 #41906] ERROR -- #<Async::IO::Socket:0x00007fba1db0c758>: Invalid argument - setsockopt(2) (Errno::EINVAL)
/Users/sloveless/.rubies/ruby-2.5.3/lib/ruby/2.5.0/forwardable.rb:229:in `setsockopt'
/Users/sloveless/.rubies/ruby-2.5.3/lib/ruby/2.5.0/forwardable.rb:229:in `setsockopt'
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-http-0.37.4/lib/async/http/server.rb:45:in `accept'
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-io-1.16.4/lib/async/io/socket.rb:68:in `block in accept_each'
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-io-1.16.4/lib/async/io/socket.rb:101:in `block in accept'
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-1.11.0/lib/async/task.rb:74:in `block in initialize'
E, [2018-11-29T17:14:46.120063 #41908] ERROR -- #<Async::IO::Socket:0x00007fba1db09a80>: Invalid argument - setsockopt(2) (Errno::EINVAL)
/Users/sloveless/.rubies/ruby-2.5.3/lib/ruby/2.5.0/forwardable.rb:229:in `setsockopt'
/Users/sloveless/.rubies/ruby-2.5.3/lib/ruby/2.5.0/forwardable.rb:229:in `setsockopt'
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-http-0.37.4/lib/async/http/server.rb:45:in `accept'
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-io-1.16.4/lib/async/io/socket.rb:68:in `block in accept_each'
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-io-1.16.4/lib/async/io/socket.rb:101:in `block in accept'
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-1.11.0/lib/async/task.rb:74:in `block in initialize'
E, [2018-11-29T17:14:48.120451 #41906] ERROR -- #<Async::IO::Socket:0x00007fba1db0c758>: Invalid argument - setsockopt(2) (Errno::EINVAL)
/Users/sloveless/.rubies/ruby-2.5.3/lib/ruby/2.5.0/forwardable.rb:229:in `setsockopt'
/Users/sloveless/.rubies/ruby-2.5.3/lib/ruby/2.5.0/forwardable.rb:229:in `setsockopt'
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-http-0.37.4/lib/async/http/server.rb:45:in `accept'
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-io-1.16.4/lib/async/io/socket.rb:68:in `block in accept_each'
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-io-1.16.4/lib/async/io/socket.rb:101:in `block in accept'
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-1.11.0/lib/async/task.rb:74:in `block in initialize'
E, [2018-11-29T17:14:50.126269 #41902] ERROR -- #<Async::IO::Socket:0x00007fba1daeb0d0>: Invalid argument - setsockopt(2) (Errno::EINVAL)
/Users/sloveless/.rubies/ruby-2.5.3/lib/ruby/2.5.0/forwardable.rb:229:in `setsockopt'
/Users/sloveless/.rubies/ruby-2.5.3/lib/ruby/2.5.0/forwardable.rb:229:in `setsockopt'
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-http-0.37.4/lib/async/http/server.rb:45:in `accept'
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-io-1.16.4/lib/async/io/socket.rb:68:in `block in accept_each'
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-io-1.16.4/lib/async/io/socket.rb:101:in `block in accept'
/Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.5.0/gems/async-1.11.0/lib/async/task.rb:74:in `block in initialize'
```

> do you mind telling me what OS, version and Rails version you are using?

You bet:

* macOS 10.14.1
* Ruby 2.5.3
* Rails 5.1.4

**Comment by ioquatix** [comment]
This is the line it's failing on, FYI:

https://github.com/socketry/async-http/blob/2e0f9f38dcf22f78d96acb3aefd4441ab1c6713b/lib/async/http/server.rb#L45

**Comment by ioquatix** [comment]
Found this interesting bug:

https://github.com/envoyproxy/envoy/blob/a8507f67225cdd912712971bf72d41f219eb74ed/source/common/network/connection_impl.cc#L201-L207

It looks like macOS (yet again) has some wonky behaviour.

**Comment by ioquatix** [comment]
@turboladen Can you please `bundle update` and try again? Thanks.

**Comment by turboladen** [comment]
Sorry for the response lag, @ioquatix; work got a little crazy there for a while. In any case, I just pulled in falcon 0.19.6 and things look great. Thanks for that! 

FWIW, here's the Gemfile.lock portion that might be of interest:

```
    falcon (0.19.6)
      async-container (~> 0.8.0)
      async-http (~> 0.37.2)
      async-io (~> 1.9)
      http-protocol (~> 0.10.0)
      localhost (~> 1.1)
      rack (>= 1.0)
      samovar (~> 1.3)
```

**Comment by brodock** [comment]
There is still something not working as expected.

I retried today with 0.24.0 and this is what I get when trying to access `localhost:3000` started with `facon serve --port 3000`:

```
 1m52s: <Async::Task:0x86d60854 failed>
      |  OpenSSL::SSL::SSLError: SSL_accept returned=1 errno=0 state=error: http request
      |  → /Users/brodock/.rvm/gems/ruby-2.5.3/gems/async-io-1.18.2/lib/async/io/generic.rb:141 in `accept_nonblock'
      |    /Users/brodock/.rvm/gems/ruby-2.5.3/gems/async-io-1.18.2/lib/async/io/generic.rb:141 in `async_send'
      |    /Users/brodock/.rvm/gems/ruby-2.5.3/gems/async-io-1.18.2/lib/async/io/generic.rb:47 in `block in wrap_blocking_method'
      |    /Users/brodock/.rvm/gems/ruby-2.5.3/gems/async-io-1.18.2/lib/async/io/ssl_socket.rb:129 in `block in accept'
      |    /Users/brodock/.rvm/gems/ruby-2.5.3/gems/async-1.15.1/lib/async/task.rb:199 in `block in make_fiber'
```

**Comment by ioquatix** [comment]
Did the browser try to connect using http or https? I noticed sometimes browser uses wrong protocol and this causes TLS to report an error.

**Comment by brodock** [comment]
@ioquatix I forced `http://` to the address. I believe this is still the same root problem reported before.

**Comment by ioquatix** [comment]
Sorry if I'm not clear on exactly what the problem is, but:

> I forced `http://` to the address. I believe this is still the same root problem reported before.

and 

> I retried today with 0.24.0 and this is what I get when trying to access `localhost:3000` started with `facon serve --port 3000`:

This seems the reason - you are trying to connect http to a server which is using https, and the server reports an error:

>       |  OpenSSL::SSL::SSLError: SSL_accept returned=1 errno=0 state=error: http request

OpenSSL even detected that the HTTP request was sent in plain text.

**Comment by brodock** [comment]
Ok, so I'm confused right now. I did not provide any configuration to falcon, does it start in "HTTPS" by default?

As before, if I use the `rails server` approach with falcon, it works as expected

**Comment by ioquatix** [comment]
Falcon defaults to `https` and `HTTP/2` by default. It prints it out when the server starts.

`rails server` uses `rackup` which is kind of the worst way to start falcon, but it conforms to the expectations of `rackup` which is `http` only:

https://github.com/socketry/falcon/blob/master/lib/rack/handler/falcon.rb#L27

AFAIK, `rackup` doesn't have enough options to support HTTP/2 & TLS, but maybe we can improve that.

Do you want to submit a PR to improve the README to make sure this behaviour is really clear?

**Comment by ioquatix** [comment]
Okay, the original issue here regarding client certificates I was able to reproduce. I think the problem is the server context was set to `VERIFY_PEER` which was causing the client certificate to be requested. I've changed this to `VERIFY_NONE` which should resolve the problem.
