### ISSUE TITLE
Odd deadlock issue in MRI.

### ISSUE THREAD

**Issue by ioquatix** [socketry/falcon#26]
I encountered this and it appears to be happening within the guts of MRI:

```
^_^ > falcon
I, [2018-10-08T17:56:11.143745 #3140]  INFO -- : Falcon taking flight! Binding to #<Falcon::Endpoint https://localhost:9292/ {}> [Async::Container::Forked with concurrency: 8]
I, [2018-10-08T17:56:11.147168 #3141]  INFO -- : Send `kill -USR1 3141` for detailed status :)
I, [2018-10-08T17:56:11.147407 #3142]  INFO -- : Send `kill -USR1 3142` for detailed status :)
I, [2018-10-08T17:56:11.147883 #3143]  INFO -- : Send `kill -USR1 3143` for detailed status :)
I, [2018-10-08T17:56:11.148314 #3144]  INFO -- : Send `kill -USR1 3144` for detailed status :)
I, [2018-10-08T17:56:11.149173 #3146]  INFO -- : Send `kill -USR1 3146` for detailed status :)
I, [2018-10-08T17:56:11.149353 #3145]  INFO -- : Send `kill -USR1 3145` for detailed status :)
I, [2018-10-08T17:56:11.150077 #3147]  INFO -- : Send `kill -USR1 3147` for detailed status :)
I, [2018-10-08T17:56:11.150695 #3148]  INFO -- : Send `kill -USR1 3148` for detailed status :)
^CTraceback (most recent call last):
	9: from /Users/samuel/.rvm/gems/ruby-2.5.1/gems/async-1.10.3/lib/async/task.rb:74:in `block in initialize'
	8: from /Users/samuel/.rvm/gems/ruby-2.5.1/gems/falcon-0.18.13/lib/falcon/command/serve.rb:110:in `block (2 levels) in run'
	7: from /Users/samuel/.rvm/gems/ruby-2.5.1/gems/async-io-1.16.1/lib/async/io/trap.rb:47:in `trap'
	6: from /Users/samuel/.rvm/gems/ruby-2.5.1/gems/async-io-1.16.1/lib/async/io/notification.rb:47:in `wait'
	5: from /Users/samuel/.rvm/gems/ruby-2.5.1/gems/async-io-1.16.1/lib/async/io/notification.rb:47:in `ensure in wait'
	4: from /Users/samuel/.rvm/gems/ruby-2.5.1/gems/async-1.10.3/lib/async/wrapper.rb:89:in `reactor='
	3: from /Users/samuel/.rvm/gems/ruby-2.5.1/gems/async-1.10.3/lib/async/wrapper.rb:193:in `cancel_monitor'
	2: from /Users/samuel/.rvm/gems/ruby-2.5.1/gems/async-1.10.3/lib/async/wrapper.rb:193:in `close'
	1: from /Users/samuel/.rvm/gems/ruby-2.5.1/gems/async-1.10.3/lib/async/wrapper.rb:193:in `deregister'
/Users/samuel/.rvm/gems/ruby-2.5.1/gems/async-1.10.3/lib/async/wrapper.rb:193:in `lock': deadlock; recursive locking (ThreadError)
```

```
> ruby --version
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin18]
```

**Comment by ioquatix** [comment]
I have not seen this happen with the latest version of MRI (2.5.3 and 2.6.0).
