### ISSUE TITLE
Flakey specs?

### ISSUE THREAD

**Issue by ioquatix** [socketry/falcon#42]
This was a one-off failure. Might be due to a clock/timing issue with certificate validity period.

```
Failures:
  1) Falcon::Server with SSL basic middleware client can get resource
     Failure/Error: response = client.get("/", {})
     
     OpenSSL::SSL::SSLError:
       SSL_connect returned=1 errno=0 state=error: certificate verify failed
     # ./vendor/bundle/ruby/2.4.0/gems/async-io-1.17.2/lib/async/io/generic.rb:128:in `connect_nonblock'
     # ./vendor/bundle/ruby/2.4.0/gems/async-io-1.17.2/lib/async/io/generic.rb:128:in `async_send'
     # ./vendor/bundle/ruby/2.4.0/gems/async-io-1.17.2/lib/async/io/generic.rb:47:in `block in wrap_blocking_method'
     # ./vendor/bundle/ruby/2.4.0/gems/async-io-1.17.2/lib/async/io/ssl_socket.rb:48:in `connect'
     # ./vendor/bundle/ruby/2.4.0/gems/async-io-1.17.2/lib/async/io/ssl_endpoint.rb:86:in `connect'
     # ./vendor/bundle/ruby/2.4.0/gems/async-http-0.37.6/lib/async/http/url_endpoint.rb:172:in `connect'
     # ./vendor/bundle/ruby/2.4.0/gems/async-http-0.37.6/lib/async/http/client.rb:117:in `block in make_pool'
     # ./vendor/bundle/ruby/2.4.0/gems/async-http-0.37.6/lib/async/http/pool.rb:127:in `create'
     # ./vendor/bundle/ruby/2.4.0/gems/async-http-0.37.6/lib/async/http/pool.rb:154:in `available_resource'[0m
     # ./vendor/bundle/ruby/2.4.0/gems/async-http-0.37.6/lib/async/http/pool.rb:116:in `wait_for_resource'
     # ./vendor/bundle/ruby/2.4.0/gems/async-http-0.37.6/lib/async/http/pool.rb:58:in `acquire'
     # ./vendor/bundle/ruby/2.4.0/gems/async-http-0.37.6/lib/async/http/client.rb:80:in `call'
     # ./vendor/bundle/ruby/2.4.0/gems/async-http-0.37.6/lib/async/http/middleware.rb:36:in `block (2 levels) in <module:Methods>'
     # ./spec/falcon/ssl_server_spec.rb:63:in `block (3 levels) in <top (required)>'
     # ./spec/falcon/ssl_server_spec.rb:49:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.4.0/gems/async-rspec-1.12.0/lib/async/rspec/reactor.rb:55:in `block (2 levels) in run_example'
     # ./vendor/bundle/ruby/2.4.0/gems/async-1.11.0/lib/async/task.rb:74:in `block in initialize'

Finished in 2.78 seconds (files took 0.42983 seconds to load)
44 examples, 1 failure, 1 pending

Failed examples:

rspec ./spec/falcon/ssl_server_spec.rb:62 # Falcon::Server with SSL basic middleware client can get resource


Falcon::Server with SSL
  basic middleware
E, [2018-12-19T23:52:47.003806 #7979] ERROR -- #<Async::IO::SSLServer:0x0000000001e42d38>: SSL_accept returned=1 errno=0 state=unknown state: sslv3 alert bad certificate (OpenSSL::SSL::SSLError)
/home/travis/build/socketry/falcon/vendor/bundle/ruby/2.4.0/gems/async-io-1.17.2/lib/async/io/generic.rb:128:in `accept_nonblock'
/home/travis/build/socketry/falcon/vendor/bundle/ruby/2.4.0/gems/async-io-1.17.2/lib/async/io/generic.rb:128:in `async_send'
/home/travis/build/socketry/falcon/vendor/bundle/ruby/2.4.0/gems/async-io-1.17.2/lib/async/io/generic.rb:47:in `block in wrap_blocking_method'
/home/travis/build/socketry/falcon/vendor/bundle/ruby/2.4.0/gems/async-io-1.17.2/lib/async/io/ssl_socket.rb:126:in `block in accept'
/home/travis/build/socketry/falcon/vendor/bundle/ruby/2.4.0/gems/async-1.11.0/lib/async/task.rb:74:in `block in initialize'
E, [2018-12-19T23:52:47.005199 #7979] ERROR -- #<Async::IO::SSLServer:0x0000000001e42d38>: SSL_accept returned=1 errno=0 state=unknown state: sslv3 alert bad certificate (OpenSSL::SSL::SSLError)
/home/travis/build/socketry/falcon/vendor/bundle/ruby/2.4.0/gems/async-io-1.17.2/lib/async/io/generic.rb:128:in `accept_nonblock'
/home/travis/build/socketry/falcon/vendor/bundle/ruby/2.4.0/gems/async-io-1.17.2/lib/async/io/generic.rb:128:in `async_send'
/home/travis/build/socketry/falcon/vendor/bundle/ruby/2.4.0/gems/async-io-1.17.2/lib/async/io/generic.rb:47:in `block in wrap_blocking_method'
/home/travis/build/socketry/falcon/vendor/bundle/ruby/2.4.0/gems/async-io-1.17.2/lib/async/io/ssl_socket.rb:126:in `block in accept'
/home/travis/build/socketry/falcon/vendor/bundle/ruby/2.4.0/gems/async-1.11.0/lib/async/task.rb:74:in `block in initialize'
    client can get resource (FAILED - 1)
```

**Comment by ioquatix** [comment]
I have not seen this issue show up since.
