### ISSUE TITLE
ipv6 problem in docker container

### ISSUE THREAD

**Issue by ts95** [socketry/falcon#56]
When I try to run `falcon serve` in a docker container I get the following errors:
```
|  4.67s: Async::IO::Socket
|       | Binding to #<Addrinfo: 127.0.0.1:8000 TCP (localhost)>
|  4.67s: Async::IO::Socket
|       | Binding to #<Addrinfo: [::1]:8000 TCP (localhost)>
|  4.67s: <Async::Task:0x2ac88aea9e94 failed>
|       |  Errno::EADDRNOTAVAIL: Cannot assign requested address - bind(2) for [::1]:8000
|       |  → /usr/local/bundle/gems/async-io-1.20.0/lib/async/io/socket.rb:216 in `bind'
|       |    /usr/local/bundle/gems/async-io-1.20.0/lib/async/io/socket.rb:216 in `block in bind'
|       |    /usr/local/bundle/gems/async-io-1.20.0/lib/async/io/socket.rb:148 in `build'
|       |    /usr/local/bundle/gems/async-io-1.20.0/lib/async/io/socket.rb:207 in `bind'
|       |    /usr/local/bundle/gems/async-io-1.20.0/lib/async/io/address_endpoint.rb:43 in `bind'
|       |    /usr/local/bundle/gems/async-http-0.38.1/lib/async/http/url_endpoint.rb:172 in `bind'
|       |    /usr/local/bundle/gems/async-io-1.20.0/lib/async/io/shared_endpoint.rb:30 in `block in bound'
|       |    /usr/local/bundle/gems/async-http-0.38.1/lib/async/http/url_endpoint.rb:183 in `block in each'
|       |    /usr/local/bundle/gems/async-io-1.20.0/lib/async/io/host_endpoint.rb:75 in `block in each'
|       |    /usr/local/lib/ruby/2.6.0/socket.rb:227 in `each'
|       |    /usr/local/lib/ruby/2.6.0/socket.rb:227 in `foreach'
|       |    /usr/local/bundle/gems/async-io-1.20.0/lib/async/io/host_endpoint.rb:74 in `each'
|       |    /usr/local/bundle/gems/async-http-0.38.1/lib/async/http/url_endpoint.rb:182 in `each'
|       |    /usr/local/bundle/gems/async-io-1.20.0/lib/async/io/shared_endpoint.rb:29 in `bound'
|       |    /usr/local/bundle/gems/falcon-0.26.0/lib/falcon/command/serve.rb:111 in `block in run'
|       |    /usr/local/bundle/gems/async-1.15.5/lib/async/task.rb:199 in `block in make_fiber'
|  4.67s: <Async::Reactor:0x2ac88aea3990 stopped=false>
|       | Exiting run-loop because finished.
| /usr/local/bundle/gems/async-io-1.20.0/lib/async/io/socket.rb:216:in `bind': Cannot assign requested address - bind(2) for [::1]:8000 (Errno::EADDRNOTAVAIL)
| 	from /usr/local/bundle/gems/async-io-1.20.0/lib/async/io/socket.rb:216:in `block in bind'
| 	from /usr/local/bundle/gems/async-io-1.20.0/lib/async/io/socket.rb:148:in `build'
| 	from /usr/local/bundle/gems/async-io-1.20.0/lib/async/io/socket.rb:207:in `bind'
| 	from /usr/local/bundle/gems/async-io-1.20.0/lib/async/io/address_endpoint.rb:43:in `bind'
| 	from /usr/local/bundle/gems/async-http-0.38.1/lib/async/http/url_endpoint.rb:172:in `bind'
| 	from /usr/local/bundle/gems/async-io-1.20.0/lib/async/io/shared_endpoint.rb:30:in `block in bound'
| 	from /usr/local/bundle/gems/async-http-0.38.1/lib/async/http/url_endpoint.rb:183:in `block in each'
| 	from /usr/local/bundle/gems/async-io-1.20.0/lib/async/io/host_endpoint.rb:75:in `block in each'
| 	from /usr/local/lib/ruby/2.6.0/socket.rb:227:in `each'
| 	from /usr/local/lib/ruby/2.6.0/socket.rb:227:in `foreach'
| 	from /usr/local/bundle/gems/async-io-1.20.0/lib/async/io/host_endpoint.rb:74:in `each'
| 	from /usr/local/bundle/gems/async-http-0.38.1/lib/async/http/url_endpoint.rb:182:in `each'
| 	from /usr/local/bundle/gems/async-io-1.20.0/lib/async/io/shared_endpoint.rb:29:in `bound'
| 	from /usr/local/bundle/gems/falcon-0.26.0/lib/falcon/command/serve.rb:111:in `block in run'
| 	from /usr/local/bundle/gems/async-1.15.5/lib/async/task.rb:199:in `block in make_fiber'
exited with code 1
```

It appears that falcon tries to bind to `[::1]:8000` and fails to do so (which makes sense since I've only exposed `127.0.0.1:8000` to the container.) Is there a way to disable ipv6?

**Comment by ioquatix** [comment]
`falcon serve --bind https://0.0.0.0:8000`

**Comment by ts95** [comment]
I tried this in the docker file `CMD falcon --verbose serve --bind https://0.0.0.0:8000` and go the same errors again 🤔

**Comment by ioquatix** [comment]
Identical?

**Comment by ts95** [comment]
Yes, but I just realized it was because I didn't rebuild the image. After rebuilding it and running it again this happened:
```
3.4s: Async::IO::Socket
    | Binding to #<Addrinfo: 0.0.0.0:8000 TCP>
3.4s: <Async::Reactor:0x2b02059d9f68 stopped=false>
    | Exiting run-loop because finished.
3.4s: #<Falcon::Endpoint http://0.0.0.0:8000/>
    | Falcon taking flight! Using Async::Container::Forked {:count=>4}
    | - To terminate: Ctrl-C or kill 7
3.4s: #<Async::Container::Forked::Instance:0x000056040b419c80>
    | - Per-process status: kill -USR1 13
        |  3.41s: #<Async::Container::Forked::Instance:0x000056040b419be0>
    | - Per-process status: kill -USR1 14
        |  3.41s: #<Async::Container::Forked::Instance:0x000056040b419bb8>
    | - Per-process status: kill -USR1 15
        |  3.41s: #<Async::Container::Forked::Instance:0x000056040b419b40>
    | - Per-process status: kill -USR1 16
```

**Comment by ts95** [comment]
Now it appears to be running properly. Thanks!
