### ISSUE TITLE
[README] Usage and integration with Rails

### ISSUE THREAD

**Issue by belgoros** [socketry/falcon#63]
As [described](https://github.com/socketry/falcon#integration-with-rails) in README I**ntegration with Rails** section:

> Alternatively run RACK_HANDLER=falcon rails server to start the server (at least, until rack#181 is merged).

1. There is a typo in the PR number, - it should be [#1181](https://github.com/rack/rack/pull/1181) instead of `#181`.
2. If point 1 is correct, the indicated PR was merged on January 4 but running `falcon serve` still raises the error:
```
Traceback (most recent call last):
	32: from /Users/Serguei/.rvm/gems/ruby-2.6.1/bin/falcon:23:in `<main>'
	31: from /Users/Serguei/.rvm/gems/ruby-2.6.1/bin/falcon:23:in `load'
	30: from /Users/Serguei/.rvm/gems/ruby-2.6.1/gems/falcon-0.30.0/bin/falcon:26:in `<top (required)>'
	29: from /Users/Serguei/.rvm/gems/ruby-2.6.1/gems/falcon-0.30.0/lib/falcon/command.rb:32:in `call'
	28: from /Users/Serguei/.rvm/gems/ruby-2.6.1/gems/samovar-2.1.1/lib/samovar/command.rb:36:in `call'
	27: from /Users/Serguei/.rvm/gems/ruby-2.6.1/gems/falcon-0.30.0/lib/falcon/command.rb:71:in `call'
	26: from /Users/Serguei/.rvm/gems/ruby-2.6.1/gems/falcon-0.30.0/lib/falcon/command/serve.rb:150:in `call'
	25: from /Users/Serguei/.rvm/gems/ruby-2.6.1/gems/falcon-0.30.0/lib/falcon/command/serve.rb:106:in `run'
	24: from /Users/Serguei/.rvm/gems/ruby-2.6.1/gems/falcon-0.30.0/lib/falcon/command/serve.rb:71:in `load_app'
	23: from /Users/Serguei/.rvm/gems/ruby-2.6.1/gems/rack-2.0.7/lib/rack/builder.rb:40:in `parse_file'
	22: from /Users/Serguei/.rvm/gems/ruby-2.6.1/gems/rack-2.0.7/lib/rack/builder.rb:49:in `new_from_string'
	21: from /Users/Serguei/.rvm/gems/ruby-2.6.1/gems/rack-2.0.7/lib/rack/builder.rb:49:in `eval'
	20: from config.ru:in `<main>'
	19: from config.ru:in `new'
	18: from /Users/Serguei/.rvm/gems/ruby-2.6.1/gems/rack-2.0.7/lib/rack/builder.rb:55:in `initialize'
	17: from /Users/Serguei/.rvm/gems/ruby-2.6.1/gems/rack-2.0.7/lib/rack/builder.rb:55:in `instance_eval'
	16: from config.ru:3:in `block in <main>'
	15: from config.ru:3:in `require_relative'
	14: from /Users/Serguei/projects/decastore/decastore-api/config/environment.rb:2:in `<top (required)>'
	13: from /Users/Serguei/projects/decastore/decastore-api/config/environment.rb:2:in `require_relative'
	12: from /Users/Serguei/projects/decastore/decastore-api/config/application.rb:1:in `<top (required)>'
	11: from /Users/Serguei/projects/decastore/decastore-api/config/application.rb:1:in `require_relative'
	10: from /Users/Serguei/projects/decastore/decastore-api/config/boot.rb:3:in `<top (required)>'
	 9: from /Users/Serguei/.rvm/rubies/ruby-2.6.1/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 8: from /Users/Serguei/.rvm/rubies/ruby-2.6.1/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 7: from /Users/Serguei/.rvm/rubies/ruby-2.6.1/lib/ruby/site_ruby/2.6.0/bundler/setup.rb:10:in `<top (required)>'
	 6: from /Users/Serguei/.rvm/rubies/ruby-2.6.1/lib/ruby/site_ruby/2.6.0/bundler.rb:107:in `setup'
	 5: from /Users/Serguei/.rvm/rubies/ruby-2.6.1/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:26:in `setup'
	 4: from /Users/Serguei/.rvm/rubies/ruby-2.6.1/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:26:in `map'
	 3: from /Users/Serguei/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/forwardable.rb:230:in `each'
	 2: from /Users/Serguei/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/forwardable.rb:230:in `each'
	 1: from /Users/Serguei/.rvm/rubies/ruby-2.6.1/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:31:in `block in setup'
/Users/Serguei/.rvm/rubies/ruby-2.6.1/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:319:in `check_for_activated_spec!': You have already activated nio4r 2.3.1, but your Gemfile requires nio4r 2.3.0. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
```

3. When started the server prepending with `bundle exec falcon server -p 3000`, it starts but in `https` mode:
```
bundle exec falcon serve -p 3000
 1.29s: #<Falcon::Endpoint https://localhost:3000/>
      | Falcon taking flight! Using Async::Container::Forked {:count=>8}
      | - To terminate: Ctrl-C or kill 28803
  1.3s: #<Async::Container::Forked::Instance:0x00007fbdca62dd80>
      | - Per-process status: kill -USR1 28805
  1.3s: #<Async::Container::Forked::Instance:0x00007fbdca62dd58>
      | - Per-process status: kill -USR1 28806
  1.3s: #<Async::Container::Forked::Instance:0x00007fbdca62dd30>
      | - Per-process status: kill -USR1 28807
  1.3s: #<Async::Container::Forked::Instance:0x00007fbdca62dd08>
      | - Per-process status: kill -USR1 28808
  1.3s: #<Async::Container::Forked::Instance:0x00007fbdca62dce0>
      | - Per-process status: kill -USR1 28809
  1.3s: #<Async::Container::Forked::Instance:0x00007fbdca62dcb8>
      | - Per-process status: kill -USR1 28810
  1.3s: #<Async::Container::Forked::Instance:0x00007fbdca62dc90>
      | - Per-process status: kill -USR1 28811
  1.3s: #<Async::Container::Forked::Instance:0x00007fbdca62dc68>
      | - Per-process status: kill -USR1 28812
...
```
In this case the front-end app cannot hit `localhost:3000` anymore:
```
Async::Task:0x3fdee4c04f9c failed>
      |   OpenSSL::SSL::SSLError: SSL_accept returned=1 errno=0 state=error: wrong version number
      |   → /Users/Serguei/.rvm/gems/ruby-2.6.1/gems/async-io-1.23.1/lib/async/io/generic.rb:208 in `accept_nonblock'
      |     /Users/Serguei/.rvm/gems/ruby-2.6.1/gems/async-io-1.23.1/lib/async/io/generic.rb:208 in `async_send'
      |     /Users/Serguei/.rvm/gems/ruby-2.6.1/gems/async-io-1.23.1/lib/async/io/generic.rb:54 in `block in wrap_blocking_method'
      |     /Users/Serguei/.rvm/gems/ruby-2.6.1/gems/async-io-1.23.1/lib/async/io/ssl_socket.rb:139 in `block in accept'
      |     /Users/Serguei/.rvm/gems/ruby-2.6.1/gems/async-1.17.1/lib/async/task.rb:204 in `block in make_fiber'
55.34s: <Async::Task:0x3fdee7402f08 failed>
...
```

But if I start the server `RACK_HANDLER=falcon rails server -e staging -p 3000` everything works as before with`puma`.

Can you please clear a little bit the way to run it on a Rails API app?

I'm using :
- Ruby `2.6.1`
- Rails `5.2.2`
- Falcon `0.30.0`

Thank you.

**Comment by ioquatix** [comment]
Cross referencing https://github.com/rack/rack/pull/1357

**Comment by ioquatix** [comment]
Sorry, they closed that PR without merging it. We just have to wait for Rack in this instance.
