### ISSUE TITLE
Failure to run while using jruby (SocketError: use ServerSocket for servers)

### ISSUE THREAD

**Issue by krainboltgreene** [socketry/falcon#64]
Not sure if this is on purpose, but just wanted to throw this out here.

```
OpenSSL implementation doesn't support ALPN.
 2.09s    error: <Async::Task:0x7d0 failed> [pid=6]
               |   SocketError: use ServerSocket for servers (http://wiki.jruby.org/ServerSocket)
               |   → org/jruby/ext/socket/RubySocket.java:253 in `listen'
               |     /home/root/application/vendor/bundle/jruby/2.5.0/gems/async-io-1.23.1/lib/async/io/shared_endpoint.rb:30 in `block in bound'
               |     /home/root/application/vendor/bundle/jruby/2.5.0/gems/async-io-1.23.1/lib/async/io/endpoint.rb:104 in `block in bound'
               |     /home/root/application/vendor/bundle/jruby/2.5.0/gems/async-http-0.39.0/lib/async/http/url_endpoint.rb:193 in `block in each'
               |     /home/root/application/vendor/bundle/jruby/2.5.0/gems/async-io-1.23.1/lib/async/io/host_endpoint.rb:84 in `block in each'
               |     org/jruby/RubyArray.java:1792 in `each'
               |     /opt/jruby/lib/ruby/stdlib/socket.rb:229 in `foreach'
               |     /home/root/application/vendor/bundle/jruby/2.5.0/gems/async-io-1.23.1/lib/async/io/host_endpoint.rb:83 in `each'
               |     /home/root/application/vendor/bundle/jruby/2.5.0/gems/async-http-0.39.0/lib/async/http/url_endpoint.rb:192 in `each'
               |     /home/root/application/vendor/bundle/jruby/2.5.0/gems/async-io-1.23.1/lib/async/io/endpoint.rb:100 in `bound'
               |     /home/root/application/vendor/bundle/jruby/2.5.0/gems/async-io-1.23.1/lib/async/io/shared_endpoint.rb:29 in `bound'
               |     /home/root/application/vendor/bundle/jruby/2.5.0/gems/falcon-0.29.0/lib/falcon/command/serve.rb:111 in `block in run'
               |     /home/root/application/vendor/bundle/jruby/2.5.0/gems/async-1.17.1/lib/async/task.rb:204 in `block in make_fiber'
bundler: failed to load command: falcon (/home/root/application/vendor/bundle/jruby/2.5.0/bin/falcon)
SocketError: use ServerSocket for servers (http://wiki.jruby.org/ServerSocket)
  org/jruby/ext/socket/RubySocket.java:253:in `listen'
  /home/root/application/vendor/bundle/jruby/2.5.0/gems/async-io-1.23.1/lib/async/io/shared_endpoint.rb:30:in `block in bound'
  /home/root/application/vendor/bundle/jruby/2.5.0/gems/async-io-1.23.1/lib/async/io/endpoint.rb:104:in `block in bound'
  /home/root/application/vendor/bundle/jruby/2.5.0/gems/async-http-0.39.0/lib/async/http/url_endpoint.rb:193:in `block in each'
  /home/root/application/vendor/bundle/jruby/2.5.0/gems/async-io-1.23.1/lib/async/io/host_endpoint.rb:84:in `block in each'
  org/jruby/RubyArray.java:1792:in `each'
  /opt/jruby/lib/ruby/stdlib/socket.rb:229:in `foreach'
  /home/root/application/vendor/bundle/jruby/2.5.0/gems/async-io-1.23.1/lib/async/io/host_endpoint.rb:83:in `each'
  /home/root/application/vendor/bundle/jruby/2.5.0/gems/async-http-0.39.0/lib/async/http/url_endpoint.rb:192:in `each'
  /home/root/application/vendor/bundle/jruby/2.5.0/gems/async-io-1.23.1/lib/async/io/endpoint.rb:100:in `bound'
  /home/root/application/vendor/bundle/jruby/2.5.0/gems/async-io-1.23.1/lib/async/io/shared_endpoint.rb:29:in `bound'
  /home/root/application/vendor/bundle/jruby/2.5.0/gems/falcon-0.29.0/lib/falcon/command/serve.rb:111:in `block in run'
  /home/root/application/vendor/bundle/jruby/2.5.0/gems/async-1.17.1/lib/async/task.rb:204:in `block in make_fiber'
```

**Comment by ioquatix** [comment]
> OpenSSL implementation doesn't support ALPN.

Can't support HTTP/2 (protocol negotiation functionality missing from OpenSSL).

> SocketError: use ServerSocket for servers

Doesn't support standard Ruby `Socket` class.

@headius was there any solution to the above?

**Comment by ioquatix** [comment]
Until JRuby addresses the issues in their network stack, there is little I can do. I would suggest that you are best to use mainline CRuby until these options mature.
