### ISSUE TITLE
Binding Issues on Linux 

### ISSUE THREAD

**Issue by destructobeam** [socketry/falcon#68]
Still unable to bind properly on Linux 5.1.15-arch1-1-ARCH

`bundle exec falcon serve` produces

```
0.08s    error: <Async::Task:0x2b1ccafd6a1c failed> [pid=23552] [2019-06-27 13:56:32 +1200]
               |   Errno::EADDRINUSE: Address already in use - bind(2) for 127.0.0.1:9292
               |   → /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/socket.rb:224 in `bind'
               |     /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/socket.rb:224 in `block in bind'
               |     /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/socket.rb:165 in `build'
               |     /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/socket.rb:223 in `bind'
               |     /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/address_endpoint.rb:43 in `bind'
               |     /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/ssl_endpoint.rb:78 in `bind'
               |     /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-http-0.46.2/lib/async/http/endpoint.rb:192 in `bind'
               |     /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/endpoint.rb:101 in `block in bound'
               |     /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-http-0.46.2/lib/async/http/endpoint.rb:203 in `block in each'
               |     /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/ssl_endpoint.rb:93 in `block in each'
               |     /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/host_endpoint.rb:84 in `block in each'
               |     /home/simon/.rbenv/versions/2.5.1/lib/ruby/2.5.0/socket.rb:227 in `each'
               |     /home/simon/.rbenv/versions/2.5.1/lib/ruby/2.5.0/socket.rb:227 in `foreach'
               |     /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/host_endpoint.rb:83 in `each'
               |     /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/ssl_endpoint.rb:92 in `each'
               |     /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-http-0.46.2/lib/async/http/endpoint.rb:202 in `each'
               |     /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/endpoint.rb:100 in `bound'
               |     /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/shared_endpoint.rb:29 in `bound'
               |     /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/falcon-0.33.11/lib/falcon/command/serve.rb:109 in `block in run'
               |     /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-1.19.0/lib/async/task.rb:210 in `block in make_fiber'
bundler: failed to load command: falcon (/home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/bin/falcon)
Errno::EADDRINUSE: Address already in use - bind(2) for 127.0.0.1:9292
  /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/socket.rb:224:in `bind'
  /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/socket.rb:224:in `block in bind'
  /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/socket.rb:165:in `build'
  /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/socket.rb:223:in `bind'
  /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/address_endpoint.rb:43:in `bind'
  /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/ssl_endpoint.rb:78:in `bind'
  /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-http-0.46.2/lib/async/http/endpoint.rb:192:in `bind'
  /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/endpoint.rb:101:in `block in bound'
  /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-http-0.46.2/lib/async/http/endpoint.rb:203:in `block in each'
  /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/ssl_endpoint.rb:93:in `block in each'
  /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/host_endpoint.rb:84:in `block in each'
  /home/simon/.rbenv/versions/2.5.1/lib/ruby/2.5.0/socket.rb:227:in `each'
  /home/simon/.rbenv/versions/2.5.1/lib/ruby/2.5.0/socket.rb:227:in `foreach'
  /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/host_endpoint.rb:83:in `each'
  /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/ssl_endpoint.rb:92:in `each'
  /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-http-0.46.2/lib/async/http/endpoint.rb:202:in `each'
  /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/endpoint.rb:100:in `bound'
  /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/shared_endpoint.rb:29:in `bound'
  /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/falcon-0.33.11/lib/falcon/command/serve.rb:109:in `block in run'
  /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-1.19.0/lib/async/task.rb:210:in `block in make_fiber'
```

Then using a Procfile with `web: bundle exec falcon serve` gives a slightly different error in that it has a command not found line.

```
14:02:50 web.1  | started with pid 24248
14:02:50 web.1  |  0.08s    error: <Async::Task:0x2ab7918b70e0 failed> [pid=24248] [2019-06-27 14:02:50 +1200]
14:02:50 web.1  |                |   Errno::EADDRINUSE: Address already in use - bind(2) for 127.0.0.1:9292
14:02:50 web.1  |                |   → /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/socket.rb:224 in `bind'
14:02:50 web.1  |                |     /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/socket.rb:224 in `block in bind'
14:02:50 web.1  |                |     /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/socket.rb:165 in `build'
14:02:50 web.1  |                |     /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/socket.rb:223 in `bind'
14:02:50 web.1  |                |     /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/address_endpoint.rb:43 in `bind'
14:02:50 web.1  |                |     /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/ssl_endpoint.rb:78 in `bind'
14:02:50 web.1  |                |     /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-http-0.46.2/lib/async/http/endpoint.rb:192 in `bind'
14:02:50 web.1  |                |     /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/endpoint.rb:101 in `block in bound'
14:02:50 web.1  |                |     /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-http-0.46.2/lib/async/http/endpoint.rb:203 in `block in each'
14:02:50 web.1  |                |     /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/ssl_endpoint.rb:93 in `block in each'
14:02:50 web.1  |                |     /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/host_endpoint.rb:84 in `block in each'
14:02:50 web.1  |                |     /home/simon/.rbenv/versions/2.5.1/lib/ruby/2.5.0/socket.rb:227 in `each'
14:02:50 web.1  |                |     /home/simon/.rbenv/versions/2.5.1/lib/ruby/2.5.0/socket.rb:227 in `foreach'
14:02:50 web.1  |                |     /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/host_endpoint.rb:83 in `each'
14:02:50 web.1  |                |     /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/ssl_endpoint.rb:92 in `each'
14:02:50 web.1  |                |     /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-http-0.46.2/lib/async/http/endpoint.rb:202 in `each'
14:02:50 web.1  |                |     /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/endpoint.rb:100 in `bound'
14:02:50 web.1  |                |     /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/shared_endpoint.rb:29 in `bound'
14:02:50 web.1  |                |     /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/falcon-0.33.11/lib/falcon/command/serve.rb:109 in `block in run'
14:02:50 web.1  |                |     /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-1.19.0/lib/async/task.rb:210 in `block in make_fiber'
14:02:50 web.1  | bundler: failed to load command: falcon (/home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/bin/falcon)
14:02:50 web.1  | Errno::EADDRINUSE: Address already in use - bind(2) for 127.0.0.1:9292
14:02:50 web.1  |   /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/socket.rb:224:in `bind'
14:02:50 web.1  |   /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/socket.rb:224:in `block in bind'
14:02:50 web.1  |   /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/socket.rb:165:in `build'
14:02:50 web.1  |   /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/socket.rb:223:in `bind'
14:02:50 web.1  |   /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/address_endpoint.rb:43:in `bind'
14:02:50 web.1  |   /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/ssl_endpoint.rb:78:in `bind'
14:02:50 web.1  |   /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-http-0.46.2/lib/async/http/endpoint.rb:192:in `bind'
14:02:50 web.1  |   /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/endpoint.rb:101:in `block in bound'
14:02:50 web.1  |   /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-http-0.46.2/lib/async/http/endpoint.rb:203:in `block in each'
14:02:50 web.1  |   /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/ssl_endpoint.rb:93:in `block in each'
14:02:50 web.1  |   /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/host_endpoint.rb:84:in `block in each'
14:02:50 web.1  |   /home/simon/.rbenv/versions/2.5.1/lib/ruby/2.5.0/socket.rb:227:in `each'
14:02:50 web.1  |   /home/simon/.rbenv/versions/2.5.1/lib/ruby/2.5.0/socket.rb:227:in `foreach'
14:02:50 web.1  |   /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/host_endpoint.rb:83:in `each'
14:02:50 web.1  |   /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/ssl_endpoint.rb:92:in `each'
14:02:50 web.1  |   /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-http-0.46.2/lib/async/http/endpoint.rb:202:in `each'
14:02:50 web.1  |   /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/endpoint.rb:100:in `bound'
14:02:50 web.1  |   /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-io-1.23.1/lib/async/io/shared_endpoint.rb:29:in `bound'
14:02:50 web.1  |   /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/falcon-0.33.11/lib/falcon/command/serve.rb:109:in `block in run'
14:02:50 web.1  |   /home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/async-1.19.0/lib/async/task.rb:210:in `block in make_fiber'
14:02:51 web.1  | exited with code 1
14:02:51 system | sending SIGTERM to all processes
```

**Comment by ioquatix** [comment]
Without falcon running `lsof -I :9292` without falcon running?

**Comment by destructobeam** [comment]
Yup, no output, if something else was running on that port version 0.31.0 wouldn't be able to bind to that address either, but it can with the --reuse-port option passed.

**Comment by ioquatix** [comment]
@destructobeam thanks for the quick reply. I understand what you are saying but I'm having a hard time reconciling it with my understanding of what Falcon is doing.

The port is bound before forking:

https://github.com/socketry/falcon/blob/6d4ef205e2ef7a7e2ab84dbcd6fd2e6ec524c68f/lib/falcon/command/serve.rb#L108-L110

That's literally where it's crashing:

```
/home/simon/development/ruby/falcon_test/vendor/ruby/2.5.0/gems/falcon-0.33.11/lib/falcon/command/serve.rb:109 in `block in run'
```

I have a weird idea.

Is it possible you list multiple times 127.0.0.1 for localhost?

Can you try the following code:

```
Async::HTTP::Endpoint.parse("https://localhost:9292").each.map{|endpoint| endpoint.endpoint.endpoint.address}
=> [#<Addrinfo: [::1]:9292 TCP (localhost)>, #<Addrinfo: 127.0.0.1:9292 TCP (localhost)>]
```

**Comment by destructobeam** [comment]
Yeah, it looks like it is coming up in the results multiple times:

```ruby
Async::HTTP::Endpoint.parse("https://localhost:9292").each.map{|endpoint| endpoint.endpoint.endpoint.address}
=> [#<Addrinfo: [::1]:9292 TCP (localhost)>, #<Addrinfo: 127.0.0.1:9292 TCP (localhost)>, #<Addrinfo: 127.0.0.1:9292 TCP (localhost)>]
```

So looked through `/etc/hosts` and it looks like there were two lines for IP4 with `localhost` set after the `.localdomain` address, have removed `localhost` after the second entry and it has fixed the issue. So maybe something to add to the README as a potential issue, as it hasn't affected anything else until this point, so could occur on other Arch systems?

**Comment by ioquatix** [comment]
Not many systems bind to all available addresses using the localhost alias. Maybe it's why it didn't show up in other systems. But surely, it's a bug with your configuration. Maybe we can at catch `Errno::EADDRINUSE` and detect the situation. Feel free to submit a PR to `async-io` if you think it makes sense.
